.gitignore
config/manager/kustomization.yaml
config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
scripts/build_and_push_images.sh

-remove bundle directory and bundle.Dockerfile before each build
-drop yq commands (no longer needed as we cleanup the above files)
-cleanup config/manager/kustomization.yaml
-add config/manager/kustomization.yaml to .gitignore (this file is
generated via the Makefile)
-uncomment the bundle validate and move it before the index gets
created

build script updates

---

containers/image_downloader/Dockerfile
containers/image_downloader/entrypoint.sh

First draft of init container that downloads images from compute node provisioning

RHEL image downloader container

---

controllers/controllervm_controller.go

The networkdata rendering is running for all controllers with the
same ControllerIP template parameter which results in with multiple
controllers that all have the same ip on the osp network. Now we
make sure that the secret gets rendered with uniq ips.

Fix controller networkdata secret generation

---

controllers/baremetalset_controller.go
pkg/baremetalset/const.go

Allows targeted BaremetalHost scale-down (via annotation) for BaremetalSets

Specific BMH scale-down

---

controllers/baremetalset_controller.go
controllers/overcloudipset_controller.go

Currently contains fixes for duplicate hostname/IP issues, as well as another problem involving a stuck reconciliation loop for BaremetalSets.  However, it does not clean-up the respective hostnames/IPs in OvercloudIpSet status nor OvercloudNet status during BaremetalSet scale-down.  We are leaving it this way for now.

IPAM BMSet scale functionality

---

.github/workflows/golangci-lint.yaml

Simple tests being moved from Travis to Github Actions.

Github actions lint,vet and unit test pipeline

---

.gitignore
Makefile
OWNERS

Use Makefile go test targets from common CI repository
Added OWNERS file required by PROW.

Add OWNERS, use test scripts from common CI repo

---

config/manager/kustomization.yaml
config/manager/service_account.yaml
config/rbac/kustomization.yaml
config/rbac/service_account.yaml
controllers/provisionserver_controller.go
pkg/provisionserver/const.go

Also moves the additonal SAs created from config/manager to config/rbac .

Run provisionserver using dedicated user

---

controllers/provisionserver_controller.go

Right now one provision server per baremetalset gets created. Since
the http port is hard coded and HostNetwork is used, only one
provisionserver pod can run on a worker node. This adds anti-affinity
to the provison server pod to prevent running more then one on a
worker node. In the future there is the plan to run a single
provisioning server hosting all images.

Add anti-affinity to provisionserver pods

---

config/manifests/bases/osp-director-operator.clusterserviceversion.yaml

Because it looks so much nicer than "Basic Install"

Declare that we support Seamless Upgrades

---

controllers/openstackbaremetalset_controller.go
controllers/openstackprovisionserver_controller.go
pkg/baremetalset/const.go
pkg/provisionserver/const.go

Just undoing certain prov server and baremetal set identifier name changes until we decide on short names

Remove long names for now

---

bindata/virtualmachine/01-virtual-machine.yaml

We also need a `StorageClass` conditional in the VM template

Small tweak to optional storage class

---

config/samples/osp-director_v1beta1_openstackvmset.yaml

Just noticed this while using the sample for some SRIOV testing

Add two missing req fields to vmset sample

---

pkg/common/funcs.go
pkg/common/network.go

Check nad CNIconfig

---

api/v1beta1/openstackbaremetalset_types.go
api/v1beta1/openstackipset_types.go
api/v1beta1/openstackvmset_types.go
config/crd/bases/osp-director.openstack.org_openstackbaremetalsets.yaml
config/crd/bases/osp-director.openstack.org_openstackipsets.yaml
config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml

Add additional shortNames for osbaremetalset, osipset and osvmset

Register additonal shortNames

---

Dockerfile

Argument is used during build process, however it was
not defined.

Add GO_BUILD_EXTRA_ARGS to the Dockerfile

---

README.md

Shows how to use `virtctl` to pre-load the RHEL base image

baseImageVolumeName README additions

---

README.md

Bullet point CRD stuff
Remove deprecation warnings when creating configmaps
Feel free to ignore, just doing this whilst doing other documentation. :)

Some README nits

---

templates/openstackephemeralheat/bin/galera.cnf
templates/openstackephemeralheat/bin/mariadb_config.json
templates/openstackephemeralheat/bin/mariadb_init_config.json

This resolves issues where mysqld wasn't reading the
provided config file

Allow mysql to read its config

---

templates/openstackplaybookgenerator/bin/create-playbooks.sh

This error somehow crept into the recent osplaybookgenerator workflow.
We were sending all the environments to the 'container image prepare'
command but only the container-image-prepare.yaml is really required.

Fix 'Property Container*Image not assigned' errors

---

controllers/openstackplaybookgenerator_controller.go

This adds some appropriate requeue's, and quiets down
some logging that were occuring when this controller
reconciled a playbookgenerator.

Fixes to playbookgenerator controller reconcile

---

README.md

Readme tweak to cd to proper directory before
running tripleo-deploy.sh

Small Readme tweak

---

controllers/openstackcontrolplane_controller.go

The osctlplane watched all pods in the openstack namespace, which
can lead in immense reconcile if playbook generator recreates its
pods again and again. This limits to reconcile the osctlplane to
pods from vmset and openstackclient having the corrsponding AppLabel.

Reduce osctlplane pod watch scope

---

controllers/openstackcontrolplane_controller.go

At the moment we run over the virtualMachineRoles and create for
the network list of the role vips for the network. If there are
multiple roles with different network list, last virtualMachineRoles
network list updates the ipset and VIPs won't get created.
This changes to create a uniq list of all networks for all
virtualMachineRoles and creates VIPs for this uniq list.

fix vip creation

---

controllers/openstackcontrolplane_controller.go
go.mod
go.sum
pkg/common/passwords.go
pkg/openstackplaybookgenerator/volumes.go
templates/openstackcontrolplane/config/tripleo-overcloud-passwords.yaml
templates/openstackplaybookgenerator/bin/create-playbooks.sh

This patch adds support for generating TripleO passwords as
a ConfigMap.

Generate TripleO passwords as ConfigMap

---

README.md
config/samples/osp-director_v1beta1_openstackplaybookgenerator.yaml
controllers/openstackplaybookgenerator_controller.go
pkg/openstackplaybookgenerator/volumes.go

This should help clarify what the ConfigMap is actually being
used for.

Rename tripleo-deploy-config-custom to heat-env-config

---

config/samples/osp-director_v1beta1_openstackbaremetalset.yaml
tests/kuttl/tests/openstackbaremetalset_scale/02-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/03-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/04-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/06-assert.yaml

This key is automatically generated by the controlplane AppLabel
name. Lets make them match.

Set deploymentSSHSecret: osp-controlplane-ssh-keys

---

controllers/openstackvmset_controller.go

As explain in code comments, the Kubevirt fencing agent needs to be able to directly call the Kubevirt API for power operators.  This is not allowed by the default `Always` run strategy.  Instead, we need to use `RerunOnFailure` which will still boot/reboot the VM on creation/failure, but also allows for direct power API calls.

Use RerunOnFailure Kubevirt run strategy for VMs

---

controllers/openstackprovisionserver_controller.go
pkg/openstackephemeralheat/heat.go
pkg/openstackephemeralheat/mariadb.go
pkg/openstackephemeralheat/rabbitmq.go
pkg/provisionserver/initcontainer.go

This updates ephemeralheat and provisionserver to use
PullAlways.

Standardize on PullAlways

---

config/rbac/role.yaml
config/rbac/service_account.yaml
controllers/openstackvmset_controller.go
go.mod
go.sum
pkg/vmset/const.go
templates/vmset/cloudinit/userdata
templates/vmset/fencing-kubeconfig/fencing-kubeconfig

Adds a service account for the Kubevirt fencing functionality, and then generates and injects a kubeconfig for that account into VMSet VMs to be used with the fencing agent

Fencing SA and associated kubeconfig

---

templates/openstackplaybookgenerator/bin/create-playbooks.sh

Since 16.2 and 17 is supported on master branch, same file gets
rendered and condition is wrong.

Fix condition for rendered parameter file

---

go.mod
go.sum

github.com/go-air/gini
Not the operator-framework version

Use go-air gini

---

Dockerfile
Dockerfile.provision-ip-discovery-agent

Change-Id: Id08e5482dc5961e467d7f4034bbae9ae6422c215

update version of Dockerfile's to 1.0.0

---

api/v1beta1/openstackephemeralheat_webhook.go
api/v1beta1/openstackprovisionserver_types.go
api/v1beta1/openstackprovisionserver_webhook.go
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
config/default/manager_auth_proxy_patch.yaml

This is to better support installing our operator in offline mode.
OSPK8-394 #comment PR posted

Use ENV variables to set Image URL defaults

---

config/manifests/bases/osp-director-operator.clusterserviceversion.yaml

OSPK8-395 #close Add relatedImages to base CSV

Add relatedImages to base CSV

---

scripts/build_and_push_images.sh

Corrects a bash error in the build script. Also runs a podman
login check to ensure users have permission to pull images
from the redhat.registry.io repo before running this script.

build script fixes: podman login check

---

api/v1beta1/openstacknetconfig_webhook.go

This adds validation check to the osnetcfg webhook to prevent bridge name changes on an update.

[OSPK8-402] Add bridge name validation to osnetcfg webhook

---

.github/create_opm_index.sh
.github/workflows/build-osp-director-operator.yaml
.github/workflows/release-osp-director-operator.yaml

Automated way of creating index image.
Re-tagging all images on prerelase and release actions.

Github workflow to tag release image and create index image

---

controllers/openstacknet_controller.go
pkg/common/network.go

Conflicts:
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
controllers/openstacknet_controller.go
pkg/openstacknetattachment/const.go
(cherry picked from commit 34abd470ca6e15ae55f625d86b31af4ab974abdd)

[OSPK8-420] set MTU on NADs

---

api/v1beta1/common_types.go
api/v1beta1/openstackclient_types.go
api/v1beta1/openstackcontrolplane_types.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackclients.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
pkg/common/configmap.go
pkg/openstackclient/volumes.go
templates/openstackclient/bin/init.sh

Required for TLS public endpoints where we cannot rely on IPA client to
install CA certs.

Add config map to install custom CA certs

---

README.md
api/v1beta1/openstacknetattachment_webhook.go
api/v1beta1/openstacknetconfig_webhook.go
controllers/openstacknetattachment_controller.go
pkg/nmstate/funcs.go

Documents how to configure jumboframes using multiple interfaces
in the desired state interfaces list.
Also improves osnetatt/nncp cleanup for this multi interface
scenario in the nncp desired state.

[OSPK8-420] Document jumbo frame config and improve cleanup

---

.github/create_bundle.sh
.github/workflows/build-osp-director-operator.yaml

Fixes issue where @sha256 was prefixed twice.

Fix github action for bundle generation.

---

api/v1beta1/common_types.go
config/samples/osp-director_v1beta1_openstackbackuprequest.yaml
controllers/openstackbaremetalset_controller.go
controllers/openstackclient_controller.go
controllers/openstackconfiggenerator.go
controllers/openstackipset_controller.go
controllers/openstackmacaddress_controller.go
controllers/openstacknet_controller.go
controllers/openstacknetattachment_controller.go
controllers/openstacknetconfig_controller.go
controllers/openstackvmset_controller.go
pkg/openstackbackup/funcs.go
tests/kuttl/common/scripts/prep.sh
tests/kuttl/tests/openstackbackuprequest_save/00-prep.yaml
tests/kuttl/tests/openstackbackuprequest_save/01-assert.yaml
tests/kuttl/tests/openstackbackuprequest_save/01-create_resources.yaml
tests/kuttl/tests/openstackbackuprequest_save/01-errors.yaml
tests/kuttl/tests/openstackbackuprequest_save/02-assert.yaml
tests/kuttl/tests/openstackbackuprequest_save/02-errors.yaml

Also fixes a few minor bugs related to backup/restore

Backup/restore KUTTL tests

---

controllers/openstackprovisionserver_controller.go

For the `OpenStackProvisionServer` controller, we were caching the first interface used (whether supplied via a CR or discovered from Metal3).  This prevented subsequent CRs with an `interface` override in the spec from properly honoring and using that chosen interface.

[OSPK8-424] Fix prov server interface override

---

api/v1beta1/openstackprovisionserver_types.go
controllers/openstackbaremetalset_controller.go
controllers/openstackprovisionserver_controller.go

Switches provision server controller to use the new deferred status approach

[OSPK8-415] Deferred status pattern for prov server

---

api/v1beta1/openstacknetconfig_webhook.go
config/default/manager_default_images.yaml

Fix deploy

---

Makefile

We use oc everywhere else and it's better to use oc.

Use oc apply in Makefile

---

api/v1beta1/openstackcontrolplane_webhook.go

For wallaby/OSP17.0 AdditionalServiceVIPs are required for Redis
and OVN DB. Right now there is only a check for the 17.0 version
and not upstream wallaby [1].
This changes to use the GetOSPVersion [2] function to map the
provided/defaulted OSPVersion.
Also adds version check to the webhook to validate a supported
version is provided in the CR if any.
[1] https://github.com/openstack-k8s-operators/osp-director-operator/blob/master/api/v1beta1/openstackcontrolplane_webhook.go#L130
[2] https://pkg.go.dev/github.com/openstack-k8s-operators/osp-director-operator/api/v1beta1#GetOSPVersion

Fix check for upstream/downstream version for AdditionalServiceVIPs

---

README.md

Some required README updates now that we have the new
deployment workflow

initial Readme updates for OSDeploy

---

api/v1beta1/openstacknetconfig_webhook.go

Adding/updating an osnetcfg to add a new attachconfig fails with
"denied the request: bridge names may not be changed".
If there is a new attachcfg added to spec.attachConfigurations
we fail to find it in the oldInstance and therefore return with
an error like the bridge name probably changed.
Instead if the attachRef is in the spec of the old CR instance
* check if bridge names did not change
* otherwise expect it to be a new attachconfiguration/interface
to configure on the workers.

[OSPK8-457] Allow adding new osnetattach definitions

---

controllers/openstackclient_controller.go

There can be a pod re-create loop in case the image of a
openstackclient changes, but the pod status does not reflect
the change of the new image in time before the new
reconcilation.
This changes to update the openstackclient image only if the
spec in the image changes and it is a pod update.

Fix openstackclient restart loop

---

pkg/openstackconfiggenerator/configmap.go
templates/openstackconfiggenerator/config/16.2/rendered-tripleo-config.yaml
templates/openstackconfiggenerator/config/17.0/rendered-tripleo-config.yaml

Tripleoclient now sets this in stable/train - https://review.opendev.org/c/openstack/python-tripleoclient/+/825689

Add CtlplaneNetworkAttribues for 16.2

---

go.mod
go.sum

Bump to Masterminds/goutils v1.1.1

---

.pull_request_pipeline
pkg/common/ipam.go
pkg/common/job_util.go
pkg/openstackconfiggenerator/configmap.go
pkg/openstackconfigversion/git_util.go

Also cherry-picks golang-ci fix

set GITHUB_BRANCH to v1.2.x

---

api/v1beta2/openstackcontrolplane_webhook.go

Right now with multiple VM roles specified conversionm to the new
rootDisk format does not work. The first VM rootDisk gets converted
and then the RootDiskConvertedAnnotation annotation set to true.
As a result the remaining VM roles don't get converted with
RootDiskConvertedAnnotation already being true.
This changes the condition when to set the RootDiskConvertedAnnotation
annotation only when all VM roles got converted.

Fix rootDisk conversion check

---

containers/agent/provision_ip_discovery.go

Container image for modified agent available here: `quay.io/andrewbays/osp-director-agent:v0.0.1`

Only accept v4 IPs for prov IP discovery

---

.pull_request_pipeline

(cherry picked from commit 3c7dbaa2cc90ad5a44f1fc5d9d6e02c6bde27436)

[v1.2.x] Fix pull trigger job names

---

.github/workflows/build-osp-director-operator.yaml

See https://github.com/openstack-k8s-operators/openstack-operator/pull/188

Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit

---

controllers/openstackprovisionserver_controller.go

Also set deployment strategy to recreate and stop logging a nil err.

[OSPK8-672] fix provisionserver localImageUrl update

---

config/default/manager_default_images_16.2.yaml
config/default/manager_default_images_17.0.yaml
config/default/manager_default_images_17.1.yaml

Fix typo in default configs

---

templates/vmset/cloudinit/userdata

link-local is not supported for loopback

Skip loopback devices when setting ipv6.method link-local

---

containers/agent/deploy.go

Missed the deploy agent when adding multiple playbook support

FFU: Fix multiple playbook support in deploy agent

---

api/v1beta1/common_openstackbaremetalset.go
api/v1beta1/openstackbaremetalset_webhook.go
controllers/openstackbaremetalset_controller.go
controllers/openstackipset_controller.go
main.go

There could be BMHs in other states and we should exclude those.

Check for Available BMHs

---

controllers/openstacknetconfig_controller.go

If the owner of an OSIPset is an OpenStackClient resource, the role name of an role reservation gets set to
<openstackclient.Role><instance.Name>. Right now this check is using an owner label, and queries if an OpenStackClient object exist with this name. In some circumstance this has seen to fail, most likely on the initial create and as a result it ended in two role reservations in the OSNet.
~~~
roleReservations:
OpenstackClientopenstackclient: <<<<<<<<<<<< good reservation
addToPredictableIPs: false
reservations:
- deleted: false
hostname: openstackclient-0
ip: x.x.x.x
serviceVIP: false
vip: false
...
openstackclient:  <<<<<<<<<<<< wrong reservation
addToPredictableIPs: false
reservations:
- deleted: true
hostname: openstackclient-0
ip: x.x.x.x
serviceVIP: false
vip: false
status: …

Make IPSet OSclient owner check more robust

---

api/v1beta1/common_openstacknet.go
api/v1beta1/common_openstacknet_test.go
controllers/openstackipset_controller.go

also adds functional test for AddOSNetNameLowerLabels and logs for IPset label update

fix AddOSNetNameLowerLabels for network delete
