controllers/provisionserver_controller.go

Metal3 will attempt to validate the image URL passed to it via BareMetalHost, so we need to wait until the ProvisionServer pod is running so that the image is actually available.

Wait for prov server pod = running

---

pkg/common/configmap.go
pkg/common/secret.go

Without this removal, if the first template in the array will prevent the remaining secrets from being created/updated in some scenarios

Don't return when secret op is not none

---

controllers/provisionserver_controller.go

This corrects an err check result so that it returns the err
if there are issues configuring configmaps.

Correct err check result in provisionserver

---

controllers/openstackclient_controller.go

This resulted in unwanted openstackclient restarts.

Fix openstack client env merge

---

controllers/controlplane_controller.go

So far the hard coded controller string was used for the ControllerVM
CR. Use the lower case role name instead.

CM cr name from role

---

api/v1beta1/baremetalset_types.go
api/v1beta1/controllervm_types.go
api/v1beta1/controlplane_types.go
config/crd/bases/osp-director.openstack.org_baremetalsets.yaml
config/crd/bases/osp-director.openstack.org_controllervms.yaml
config/crd/bases/osp-director.openstack.org_controlplanes.yaml
controllers/baremetalset_controller.go
controllers/controllervm_controller.go
controllers/controlplane_controller.go
templates/baremetalset/cloudinit/userdata
templates/controllervm/cloudinit/userdata

if PasswordSercret parameter is provided in the CR the controllers
set the root password via cloud init for the root user. It is expected
that the PasswordSercet data has a NodeRootPassword key with a plane
text password.

support customized root pwd

---

api/v1beta1/controllervm_types.go
api/v1beta1/controlplane_types.go
bindata/cdi/01-cdi-base-image.yaml
config/crd/bases/osp-director.openstack.org_controllervms.yaml
config/crd/bases/osp-director.openstack.org_controlplanes.yaml
config/samples/osp-director_v1beta1_controllervm.yaml
config/samples/osp-director_v1beta1_controlplane.yaml
controllers/controllervm_controller.go
controllers/controlplane_controller.go

This can be used to customize the storageClass used for
DataVolume imports. Under certain situation (dev environments)
this is beneficial for performance reasons.

Add imageImportStorageClass

---

config/manager/kustomization.yaml
config/rbac/service_account.yaml
controllers/openstackclient_controller.go
pkg/openstackclient/const.go

create osp-director-operator-openstackclient user and use it for
creating the openstackclient pod with no permissions to connect to
the OCP API.

Use dedicated user for openstackclient pod

---

controllers/openstackclient_controller.go
pkg/common/pvc.go
pkg/openstackclient/const.go
pkg/openstackclient/initcontainer.go
pkg/openstackclient/volumes.go
templates/openstackclient/bin/init.sh
templates/openstackclient/bin/tripleo-deploy.sh

Move deployment operations to cloud-admin user and use a pvc as
the home directory to have everything in /hob/cloud-admin persistent.
Also use pvc for /etc/hosts to have entries added by the tripleo
deployment persistent.

Use pvc for cloud-admin home directory

---

api/v1beta1/baremetalset_types.go
config/crd/bases/osp-director.openstack.org_baremetalsets.yaml
config/samples/osp-director_v1beta1_baremetalset.yaml
controllers/baremetalset_controller.go
templates/baremetalset/cloudinit/networkdata

The mgmtInterface was used as ctlplane interface. Lets rename the
interface to what it is actually used for. Adding mgmt interface
to the baremetalset is tracked in
https://github.com/openstack-k8s-operators/osp-director-operator/issues/113

Rename mgmtInterface to ctlplaneInterface

---

api/v1beta1/controlplane_types.go
api/v1beta1/vmset_types.go
bindata/cdi/01-cdi-base-image.yaml
bindata/virtualmachine/01-virtual-machine.yaml
config/crd/bases/osp-director.openstack.org_controlplanes.yaml
config/crd/bases/osp-director.openstack.org_vmsets.yaml
config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
config/samples/osp-director_v1beta1_controlplane.yaml
controllers/controlplane_controller.go
controllers/vmset_controller.go

This patch adds baseImageVolumeName and removes imageImportStorageClass.
By allowing an external baseImageVolume to be specified we allow
end users to pre-create their own DataVolume in any manner they choose
thus optimizing base image imports for their environments.
Specifying a baseImageVolume will effectively disable the baseImageURL
param although baseImageURL is still left as required for now
until we get validation hooks enabled to enforce either/or
validation across these two parameters.

Add baseImageVolumeName

---

config/manifests/bases/osp-director-operator.clusterserviceversion.yaml

This marks the ipset and provisioner APIs as internal
within the CSV. This will have the effect of hiding these
APIs within the OLM web console.

Mark ipsets and provisioner as internal

---

controllers/vmset_controller.go
go.mod
go.sum

Fixes an issue where VMSet generated infinite host names and empty IP addresses by using VMSet role names (plus an index) as the "host key" for VMSet host name generation.  To reproduce this beforehand, create a VMSet with differing instance name and role name (i.e. osp-database and database, respectively).

Use lowercase role names for host names

---

api/v1beta1/vmset_types.go
api/v1beta1/vmset_webhook.go
config/crd/bases/osp-director.openstack.org_vmsets.yaml

Makes VMSet `baseImageURL` and `baseImageVolumeName` optional, but requires one of them to be set

Make VMSet baseImageURL optional

---

api/v1beta1/baremetalset_types.go
api/v1beta1/baremetalset_webhook.go
config/crd/bases/osp-director.openstack.org_baremetalsets.yaml
controllers/baremetalset_controller.go
controllers/vmset_controller.go

This adds a new ProvisionServerName to BaremetalSet that
can be used as an alternate to RhelImageUrl.
Also updates BaremetalSet so that either RhelImageUrl or
ProvisionServerName needs to be set.
Pre-creating a ProvisionServer is desirable if you plan on sharing
the same image with multiple BaremetalSets. Also, pre-creating a
provisionserver should speed up future demos.

Add ProvisionServerName to BaremetalSet CR

---

controllers/openstackclient_controller.go
pkg/openstackclient/const.go

[1] adds the changes to tripleoclient so that we can use the tripleo
container image instead of our curr current created. This allign
cloud-admin uid with tripleoclient image form [1].
[1] https://review.opendev.org/c/openstack/tripleo-common/+/776174

Use tripleoclient from tripleo

---

api/v1beta1/openstackcontrolplane_types.go
api/v1beta1/openstackvmset_types.go
bindata/cdi/01-cdi-base-image.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
controllers/openstackcontrolplane_controller.go
controllers/openstackvmset_controller.go

StorageClass can be optional to use the cluster default.

Make storageClass optional

---

config/crd/patches/cainjection_in_openstackbaremetalsets.yaml
config/crd/patches/cainjection_in_openstackclients.yaml
config/crd/patches/cainjection_in_openstackcontrolplanes.yaml
config/crd/patches/cainjection_in_openstackipsets.yaml
config/crd/patches/cainjection_in_openstacknets.yaml
config/crd/patches/cainjection_in_openstackprovisionservers.yaml
config/crd/patches/cainjection_in_openstackvmsets.yaml
config/crd/patches/webhook_in_openstackbaremetalsets.yaml
config/crd/patches/webhook_in_openstackclients.yaml
config/crd/patches/webhook_in_openstackcontrolplanes.yaml
config/crd/patches/webhook_in_openstackipsets.yaml
config/crd/patches/webhook_in_openstacknets.yaml
config/crd/patches/webhook_in_openstackprovisionservers.yaml
config/crd/patches/webhook_in_openstackvmsets.yaml

The patch files in `config/crd/patches` were still targeting `v1beta` CRDs, and need to target `v1` now instead

Change CRD patches to v1

---

pkg/overcloudipset/configmap.go

The DefaultCount for the Compute is 1, set ComputeCount to 0 in
the rendered deploy environment file if no Compute baremetalset
got created that we can deploy a controlplane only overcloud.

Set ComputeCount: 0 if no baremetalset created

---

.github/workflows/golangci-lint.yaml

Pin golangci-lint to the latest stable version and increase
default timeout which was 1m.

Fix golangci github action

---

Dockerfile
config/rbac/role.yaml
controllers/openstackvmset_controller.go

Removes bindata from Dockerfile and temporarily moves net-attach-def perms to cluster-scope for the meantime

Small bindata + net-att-def cleanup

---

config/rbac/role.yaml
controllers/openstackclient_controller.go
controllers/openstackvmset_controller.go
tests/kuttl/tests/openstackcontrolplane_scale/01-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/02-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/03-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/04-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/05-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/06-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/06-errors.yaml

Includes a change to `net-attach-def` perms and networking checks in `OpenStackVmset` and `OpenStackClient` controllers

Kuttl tests for new networking arch

---

templates/openstackclient/bin/tripleo-deploy.sh

[1] is part of quay.io/openstack-k8s-operators/tripleo-deploy:16.2_20210309.1
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1927796
Depends-On: https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/86

remove sed to set rc value with [1] merged

---

api/v1beta1/openstackclient_types.go
api/v1beta1/openstackcontrolplane_types.go
config/crd/bases/osp-director.openstack.org_openstackclients.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/samples/osp-director_v1beta1_openstackclient.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane_with_additional_custom_role.yaml
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
pkg/openstackclient/const.go
tests/kuttl/tests/openstackcontrolplane_scale/02-assert.yaml

Adds OpenStackClientStorageClass parameter to the controlplane
CRD to be able to controll the storage class the pvc for the
openstackclient gets created.

Remove hard coded OpenStackClient storageClass

---

Dockerfile

To automatically create OSBS compatible Dockerfile both upstream
and downstream should be similar and controlled by args that
are different.

Adjust Dockerfile to be osbs friendly.

---

config/manager/manager.yaml

The default CPU and memory limit were low and causing the operator to be `OOMKilled`

Increase operator CPU and mem allowance

---

api/v1beta1/openstackvmset_types.go
controllers/openstackvmset_controller.go

Moves the initialization/generation of the `baseImageName` to earlier in the VMSet logic, and sets either the default or the CR spec's value as its value.  That value is then passed to the functions that need it.

Allow baseImageVolumeName to be truly optional

---

templates/openstackclient/bin/tripleo-deploy.sh
templates/openstackipset/config/mandatory.yaml

Ordering of the environment files was wrong and the
OS::Tipleo::Network::<network> were not created. As a result the
net_cidr_map entries for the different networks fell back to the
ctlplane network. This changes the ordering of the environment
files in tripleo-deploy.sh and also sets ManageNetworks: False
that the neutron resources for the networks won't get created.

Fix isolated networks and disable neutron net creation

---

README.md
controllers/openstackcontrolplane_controller.go
controllers/openstackipset_controller.go
pkg/openstackclient/volumes.go
pkg/overcloudipset/configmap.go
templates/openstackclient/bin/init.sh
templates/openstackclient/bin/tripleo-deploy.sh
templates/openstackipset/config/deployed-server-map.yaml

Adds support for Compute nodes also be Ceph OSP nodes.
Also splits the tripleo-deploy.sh to have -r and -p option for
the two phases:
-r use ephemeral heat to render the ansible playbooks
-p run ansible playbooks
With this we can control which part of the deployment process
to run.
Note: right now skip-tags opendev-validation-ceph gets added to
the deployment command if IsHCI is set on a baremetalset. Ceph
validations check verify if lvm2 package is installed. The check
verifies if the package is in any host of the ansible facts, which
includes the "undercloud". Since the lvm2 package is not installed
in the openstackclient container image this fails.

Support deploy ComputeHCI

---

Dockerfile
Dockerfile.provision-ip-discovery-agent
containers/image_downloader/Dockerfile

Updated Dockerfile for the image_downloader container that
allows to translate from upstream to downstream using
dockerfile_to_osbs.sh from openstack-k8s-operators-ci.

Image downloader Dockerfile to meet CPaaS requirements

---

README.md
api/v1beta1/openstackcontrolplane_types.go
api/v1beta1/openstackvmset_types.go
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane_with_additional_custom_role.yaml
config/samples/osp-director_v1beta1_openstackvmset.yaml
controllers/openstackcontrolplane_controller.go
controllers/openstackvmset_controller.go
templates/vmset/cloudinit/networkdata

Document usage of biosdev names for osvmset and osbmset and
introduce parameter to set ctlplane interface for vmset, which
defaults to enp2s0 and usually won't need to be changed.

Use biosdev nic naming for overcloud nodes

---

pkg/openstackephemeralheat/rabbitmq.go

This bumps the RABBITMQ_IO_THREAD_POOL_SIZE to 128 to avoid
"Failed to create thread" aborts on some machines with a larger
number of cores.

rabbitmq: bump RABBITMQ_IO_THREAD_POOL_SIZE

---

api/v1beta1/openstackprovisionserver_types.go
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
controllers/openstackprovisionserver_controller.go

Tucking this away in the `OpenStackProvisionServer` for now, but basically this allows a user to deploy a provision server on worker nodes and also select a specific interface to examine to acquire an associated IP address.  Normally we look for the Metal3 `Provisioning` CRD's specified interface, but the fact of the matter is that the actual `OpenStackProvisionServer` pod's Apache process listens on all IPs on the host (`Listen [::]:<port>`).  This might allow for more flexibility down the road if we needed to acquire a prov server's IP from a different interface (and we have at least seen one request for this use case from the field).  NOTE: `OpenStackBaremetalSet` will continue to deploy prov servers that use the Metal3 provisioning interface.  This does not change the default …

Add intf selection option to prov server

---

templates/openstackplaybookgenerator/bin/create-playbooks.sh

When custom roles are used, where there is no CountDefault in the
role, the container image prepare command will not add the container
images to the resulting tripleo-overcloud-images.yaml . Always add
our hostnamemap.yaml file, whsets the number of nodes deployed
to the role.

Fixes for playbookgenerator script

---

README.md
templates/openstackipset/config/deployed-server-map.yaml

"Add support in tripleo for distributed vlan traffic in ovn"
( https://bugs.launchpad.net/tripleo/+bug/1881593 ) was backported
to 16.2, which creates an OVNMacAddressNetwork and OVNMacAddressPort
per compute to configure the ovn chassis.
Right now we don't support MAC address management via the operator.
For now set OVNMacAddressNetwork and OVNMacAddressPort to None, which
should not affect the default geneve NeutronNetworkType. If VLAN is
used, FIP traffic does not pass to a VLAN tenant network with ML2/OVN
and DVR. DVR is enabled by default. If you need VLAN tenant networks
with OVN, you can disable DVR. To disable DVR, inlcude the following
lines in an environment file:
```yaml
parameter_defaults:
NeutronEnableDVR: false
```

For now set OVNMacAddressNetwork and OVNMacAddressPort to None

---

config/rbac/role.yaml
controllers/openstackplaybookgenerator_controller.go

We are missing a `watch` permission on `Jobs` for the OSPG controller.  This change will fix this message repeating in the operator logs:
```
E0601 18:31:53.267645       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Job: unknown (get jobs.batch)
E0601 18:31:53.970255       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Job: unknown (get jobs.batch)
```

Add watch perm for jobs

---

templates/openstackclient/bin/tripleo-deploy.sh

The init() function can fail to initialize the latest tag
if the the most recent branch is '-> HEAD'. This updates
the script to exclude that from the listing when detecting
the latest branch.

tripleo-deploy.sh init() git fix

---

config/rbac/service_account.yaml
pkg/openstackephemeralheat/const.go
pkg/openstackephemeralheat/heat.go
pkg/openstackephemeralheat/mariadb.go
pkg/openstackephemeralheat/rabbitmq.go

When running the operator local, openstackplaybookgenerator fails
to create heat-engine replica pods due to security context settings:
```
$ oc get pods
NAME                               READY   STATUS    RESTARTS   AGE
default                            1/1     Running   0          28s
default-895tm                      0/1     Error     2          27s
default-8zrqd                      0/1     Error     2          27s
default-k8jhw                      0/1     Error     2          27s
$ oc logs default-895t
+ sudo -E kolla_set_configs
sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted
sudo: no valid sudoers sources found, quitting
sudo: setresuid() [0, 0, 0] -> [1000660000, -1, -1]: Operation not permitted
sudo: unable to initialize policy plugin
$ oc get rs default
... …
```

Use dedicated service account and RunUser for playbookgenerator

---

config/crd/bases/osp-director.openstack.org_openstackplaybookgenerators.yaml
controllers/openstackplaybookgenerator_controller.go

This introduce a condtion to wait for all osbms and osvmset to
be in provisioned state before running the playbook rendering
job. With this we can be sure all resources are up before we
generate the playbooks or the user can run them.

Verify node status before run playbook job

---

README.md
templates/baremetalset/cloudinit/userdata
templates/openstackclient/bin/tripleo-deploy.sh
templates/vmset/cloudinit/userdata

This removes the installation of rhos-release package vi cloud-init
and documents the procedure how to register the overcloud nodes
via ansible to RHSM/Satellite.
Also moves the checkout of the accepted rendered playbooks to the
tripleo-deploy.sh -a action that the updated inventory.yaml file
is available to be used to register the overcloud nodes before
running the playbooks with -p.
Depends-On: https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/146

Remove rhos-release and document rhsm usage

---

api/v1beta1/openstacknet_types.go
api/v1beta1/openstackvmset_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/osp-director.openstack.org_openstacknets.yaml
config/samples/osp-director_v1beta1_openstacknet.yaml
config/samples/osp-director_v1beta1_openstacknet_ctlplane.yaml
config/samples/osp-director_v1beta1_openstacknet_external.yaml
config/samples/osp-director_v1beta1_openstacknet_internalapi.yaml
config/samples/osp-director_v1beta1_openstacknet_storage.yaml
config/samples/osp-director_v1beta1_openstacknet_storagemgmt.yaml
config/samples/osp-director_v1beta1_openstacknet_tenant.yaml
controllers/openstackclient_controller.go
controllers/openstacknet_controller.go
controllers/openstackvmset_controller.go
tests/kuttl/tests/openstackcontrolplane_scale/01-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/02-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/03-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/04-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/05-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/06-assert.yaml

At the moment we create for each network a nncp and a
network-attachment-definition corrensponding to the network name.
This results in duplicate nncp for the same bridge if more then
one network use the same bridge which can result in config race.
This patch changes the nncp creation to create the nncp for the
bridge instead of the network. With this we only create a single
nncp for required bridges.
Notes:
- this change only creates/updates the nncp for the desired
config in the osnet cr. It does not verify if the config is
different from what the current nncp might be. In case two
networks use the same bridge name, but different interfaces,
resulting from a typo/missconfig. The nncp gets updated and
might result in an update loop.
- since the osnet controller waits for the nncp to be …

Change nncp to be network independent

---

api/v1beta1/openstackclient_types.go
config/crd/bases/osp-director.openstack.org_openstackclients.yaml
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
pkg/openstackclient/volumes.go
templates/openstackclient/bin/init.sh
templates/openstackclient/bin/tripleo-deploy.sh

To use the openstackclient CRD for other purposes, like running
tempest using a tempest container image, the osclient CRD needs
to be more generic.
This makes DeploymentSSHSecret, GitSecret, and CloudName optional
parmeters and introduce RunUID and RunGID parameters which default
to the cloud-admin (42401) to be able to run pods using other/
custom users.
Also modifies the tripleo-deploy.sh to
* create ~/.config/openstack and copies the clouds.yaml there
instead of the current ~/tripleo-deploy directory. /home/cloud-admin
is a persistent storage so we can place it in the users home
directory. This resolves an issue where the openstackclient
pod gets recreated and the default /etc/openstack/clouds.yaml
is lost and would need to be copied from ~/tripleo-deploy/clouds.yaml
* adds ANSIBLE* …

Make openstackclient CRD more generic

---

tests/kuttl/tests/openstackbaremetalset_scale/02-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/03-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/04-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/06-assert.yaml

I probably should have just rebased the last OSBMS PR.  Anyhow, these changes fix the OSBMS KUTTL test for those changes.

OSBMS KUTTL scale test fixes

---

controllers/openstacknet_controller.go
go.mod
pkg/openstacknet/funcs.go
tests/kuttl/tests/openstacknet_cleanup_nncp/00-prep.yaml
tests/kuttl/tests/openstacknet_cleanup_nncp/01-assert.yaml
tests/kuttl/tests/openstacknet_cleanup_nncp/01-create_openstacknets.yaml
tests/kuttl/tests/openstacknet_cleanup_nncp/02-assert.yaml
tests/kuttl/tests/openstacknet_cleanup_nncp/02-delete_openstacknet.yaml
tests/kuttl/tests/openstacknet_cleanup_nncp/02-errors.yaml
tests/kuttl/tests/openstacknet_cleanup_nncp/03-delete_openstacknet.yaml
tests/kuttl/tests/openstacknet_cleanup_nncp/03-errors.yaml

Adds a finalizer to handle the case when all OSNets specifying a particular bridge have been deleted.  If an OSNet is deleted and no other OSNets remain that target that bridge, the underlying NNCP will be removed.  NOTE: This does not handle the case where the user might change the name of the bridge in an OSNet.  We'll need to address that in another patch, one way or another.

OSNet finalizer for NNCP removal

---

controllers/openstackclient_controller.go

If multiple OpenStackClient CRs get created the created right now
the IPset with the same Role parameter. This results in the
OpenStackClient pods to use the same IP addresses because the
OSNet reservations are grouped by the Roles.
This change adds the OpenStackClient CR name to the OpenStackClient
Role name const to make sure the Role name passed to create the
IPSet CR is uniq.

Make sure OpenStackClient creates IPset with uniq Role

---

kuttl-test.yaml
tests/kuttl/tests/openstackbaremetalset_scale/03-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/04-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/05-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/06-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/02-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/03-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/04-assert.yaml
tests/kuttl/tests/openstackcontrolplane_scale/05-assert.yaml

Increases global timeout of KUTTL tests to 3 minutes.  Also fixes a few tests that needed updating due to recent changes.

Increase KUTTL test timeout

---

controllers/openstackcontrolplane_controller.go
pkg/controlplane/const.go
pkg/openstackplaybookgenerator/volumes.go

Right now on every reconcile the tripleo-passwords get created
and the secret updated. The tripleo-passwords should only be created
once if the secret don't exist.

Generate tripleo-passwords only once

---

templates/openstackplaybookgenerator/bin/create-playbooks.sh

This changes the order of the password environment file provided
to the stack created command. With this it is possible to customize
passwords for testing via the TripleoCustomDeployFiles.

Change order in stack created command to overwrite password

---

config/samples/osp-director_v1beta1_openstackbaremetalset.yaml
config/samples/osp-director_v1beta1_openstackprovisionserver.yaml
tests/kuttl/tests/openstackbaremetalset_scale/02-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/03-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/04-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/06-assert.yaml

Adjusts KUTTL tests to use the shared URL structure for RHEL image locations
Depends-on: https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/172

Use consolidated img URLs in KUTTL

---

controllers/openstackbaremetalset_controller.go
controllers/openstackvmset_controller.go
pkg/common/const.go

Adds a label to network data secrets in `VMSets` and `BMSets` to indicate that they are safe to collect via `must-gather`.

Add label for must-gather-safe secrets

---

controllers/openstackbaremetalset_controller.go
tests/kuttl/tests/openstackbaremetalset_scale/07-assert.yaml

Somehow I removed the `must-gather` label for secrets for OSBMS.  This PR puts it back.

Re-add must-gather secret label to OSBMS controller

---

controllers/openstackbaremetalset_controller.go
controllers/openstackvmset_controller.go
pkg/common/const.go
tests/kuttl/tests/openstackbaremetalset_scale/07-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/00-prep.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/01-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/01-create_openstackprovisionserver.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/02-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/02-create_openstackprovisionserver.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/03-create_openstackprovisionserver.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/03-errors.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/04-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/04-create_openstacknet.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/05-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/05-create_openstackbaremetalset.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/06-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/06-create_openstackbaremetalset.yaml

Adds `OsProvServer` httpd port improvements for OSP 16, and also adds missing `must-gather` secret labelling for network data `Secrets`

OsProvServer port fixes + must-gather secret label, OSP 16

---

containers/provision_ip_discovery_agent/start.go

This drops the sriov version dependency and log
statement from the provisionserver container
(shouldn't be needed)

Drop SRIOV version dep from provserver container

---

api/v1beta1/openstackprovisionserver_types.go
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
templates/openstackprovisionserver/config/httpd.conf

Update the OpenStackProvisionServer defaults so that we use
registry.redhat.io/rhel8/httpd-24:1-152 as our default image.
Also fixes a functional issue with this image so that ServerRoot
is set correctly.

provisionserver: default to rhel8/httpd-24:1-152

---

api/v1beta1/openstackephemeralheat_webhook.go
api/v1beta1/openstackprovisionserver_types.go
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
config/samples/osp-director_v1beta1_openstackclient.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane_with_additional_custom_role.yaml
config/samples/osp-director_v1beta1_openstackplaybookgenerator.yaml

This should act as the 'latest' 16.2 and is what we default
to in containers-image-prepare via tripleoclient so it should be
a better default.
Also, use the 'latest' tag for the rhel8/httpd-24.

Use 16.2 instead of more specific tags

---

api/v1beta1/openstackephemeralheat_webhook.go
config/samples/osp-director_v1beta1_openstackclient.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane_with_additional_custom_role.yaml
config/samples/osp-director_v1beta1_openstackplaybookgenerator.yaml

NOTE: I have pinned the tripleoclient to 16.2.0 instead
of 16.2 because that tag doesn't yet exist. See also:
https://bugzilla.redhat.com/show_bug.cgi?id=2005107

Update OSP images to release version with 16.2 tag

---

templates/openstackplaybookgenerator/bin/create-playbooks.sh

This reverts commit ed95a0565c86fccfd123985434eafa7b50277054.
JRA-OSPK8-350 #comment Re-adds support for OSP16 to create-playbooks.sh

Revert "Drop OSP16 support from create-playbooks.sh"

---

.pull_request_pipeline

Updated pipeline file that include GITHUB_BRANCH variable.
Unfortunately Jenkins multibranch do not pass the target
branch name, so this file will need to be kept updated
for every branch containing fixed name.

Updated jenkins pipeline to include branch name

---

controllers/openstackprovisionserver_controller.go
pkg/openstackephemeralheat/heat.go
pkg/openstackephemeralheat/mariadb.go
pkg/openstackephemeralheat/rabbitmq.go
pkg/provisionserver/initcontainer.go

This updates ephemeralheat and provisionserver to use
PullAlways.
(backported from master)
Depends on https://github.com/openshift/release/pull/21716

Standardize on PullAlways

---

api/v1beta1/openstackcontrolplane_types.go
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/rbac/service_account.yaml
controllers/openstackplaybookgenerator_controller.go
controllers/openstackvmset_controller.go
pkg/common/configmap.go
pkg/common/const.go
pkg/common/fencing.go
pkg/common/secret.go
pkg/common/template_util.go
pkg/vmset/const.go
templates/openstackplaybookgenerator/config/fencing.yaml
templates/vmset/cloudinit/userdata

1. OSVMSet controller creates namespace-scoped secrets needed for fencing considerations, instead of relying on OLM (which had a race condition)
2. Allows config maps and secrets to have annotations
3. Allows secrets to set a secret type (instead of only Opaque)
4. Adds functionality to unzip custom heat tarballs to detect custom roles that use Pacemaker

Kubeconfig for fencing, part 2

---

containers/image_downloader/Dockerfile

To allow automation we requre moving all differences between
upstream and OSBS containers to be defined as ARGs.

Image downloader move name and version to ARG

---

templates/openstackplaybookgenerator/bin/create-playbooks.sh

Make sure /usr/share/openstack-tripleo-heat-templates is also removed
in any file added via the tht tar file. E.g. in the provided nic templates.

Fix default tht dir replacement

---

templates/openstackplaybookgenerator/bin/create-playbooks.sh

Avoids the following message on git clone/checkout:
warning: remote HEAD refers to nonexistent ref, unable to checkout.

Initialize playbook git masters with README

---

api/v1beta1/openstackprovisionserver_types.go
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml

there were several images pointing to beta instead of tech-preview
Change-Id: Ia160f1737ef17c950fe0c579b52aa2d276f747d0

fixup references to rhosp-beta-rhel8 images

---

Makefile
api/v1beta1/openstackbaremetalset_webhook.go
api/v1beta1/openstackcontrolplane_webhook.go
api/v1beta1/openstackephemeralheat_webhook.go
api/v1beta1/openstacknet_webhook.go
api/v1beta1/openstackprovisionserver_webhook.go
api/v1beta1/openstackvmset_webhook.go
config/crd/bases/osp-director.openstack.org_openstackbaremetalsets.yaml
config/crd/bases/osp-director.openstack.org_openstackclients.yaml
config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/crd/bases/osp-director.openstack.org_openstackephemeralheats.yaml
config/crd/bases/osp-director.openstack.org_openstackipsets.yaml
config/crd/bases/osp-director.openstack.org_openstackmacaddresses.yaml
config/crd/bases/osp-director.openstack.org_openstacknets.yaml
config/crd/bases/osp-director.openstack.org_openstackplaybookgenerators.yaml
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
config/default/webhookcainjection_patch.yaml
config/webhook/manifests.yaml

Updates to make operator SDK 1.13.1 function properly with our existing operator config and code

Bump ctrl-gen version for OpSDK 1.13.1

---

controllers/openstackplaybookgenerator_controller.go

Role names for VMs belonging to `OsVMSets` for `OsControlPlanes` are ultimately stored as a lowercase label value in the child `VirtualMachineInstance` resources.  This might have changed in the past month or so, as we used to query against the capitalized role name for fencing data generation purposes (and it worked).  Anyhow, using lowercase role names fixes the problem and allows proper fencing config YAML generation.

Use lowercase role names to get VMs for fence CM generation

---

scripts/stage_downstream_rebase.sh

This script helps push rebase commits downstream
and rebuilds the associated bundle container files
for that commit.
There are some definate release automation improvements we
might could make based on the logic here. Specifically
with regards to the dependency between the bundle image
and the final image:tag of the operator image.

Add script to help stage downstream rebases

---

.github/create_bundle.sh
.github/workflows/build-osp-director-operator.yaml

Red Hat github action is used to build osp-director-operator
images:
- osp-director-operator
- rhel-downloader
- provision-ip-discovery-agent
- osp-director-operator-bundle
The images are tagged with the sha and latest.

Use github action to build osp-director-operator images

---

api/v1beta1/openstackclient_types.go
api/v1beta1/openstackcontrolplane_types.go
config/crd/bases/osp-director.openstack.org_openstackclients.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
pkg/openstackclient/const.go
pkg/openstackclient/volumes.go
templates/openstackclient/bin/init.sh
templates/openstackclient/bin/kolla_config.json
templates/openstackclient/bin/kolla_config_init.json

Add secret to pass IPA config and admin creds to configure IPA client on
openstackclient pod.
Use kolla-config to persist files created/modified by IPA client install.

Configure IPA client on openstackclient pod

---

PROJECT
README.md
api/v1beta1/openstacknet_types.go
api/v1beta1/openstacknet_webhook.go
api/v1beta1/openstacknetconfig_types.go
api/v1beta1/openstacknetconfig_webhook.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/osp-director.openstack.org_openstacknetconfigs.yaml
config/crd/bases/osp-director.openstack.org_openstacknets.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
controllers/openstackipset_controller.go
controllers/openstacknetconfig_controller.go
main.go
pkg/common/template_util.go
pkg/openstackipset/configmap.go
pkg/openstacknet/const.go
templates/openstackipset/config/16.2/network_data.yaml
templates/openstackipset/config/16.2/rendered-tripleo-config.yaml
templates/openstackipset/config/17.0/network_data.yaml
templates/openstackipset/config/17.0/rendered-tripleo-config.yaml

Renders DeployedNetworkEnvironment and CtlplaneNetworkAttributes from network information required by wallaby/OSP17 networkv2.
New Parameters:
- IsControlPlane to make it easier to identify controlplane network which is kind of special network from ooo side. The webhook sets the parameter automatically for the default ctlplane names when Name is "Control" or NameLower "ctlplane".
Parameters required to render DeployedNetworkEnvironment and CtlplaneNetworkAttributes:
- DomainName the name of the dns domain, this is used to create the per ooo network domain name, like `internalapi.osptest.test.metalkube.org`
- DNSServers list of dns servers
- DNSSearchDomains list of DNS search domains
TODO - in a follow up we probably want to:
* change osctlplane and osbms to get the dns servers from the …

[OSPK8-324 OSPK8-325] DeployedNetworkEnvironment and CtlplaneNetworkAttributes

---

controllers/openstackconfiggenerator.go
controllers/openstacknetattachment_controller.go
controllers/openstacknetconfig_controller.go
pkg/common/configmap.go
pkg/common/secret.go

Right now on every reconcile messages get logged, even if there
was no action.
To make logging better readable/ easier to follow, this change
logs the condition messages in the defer function where we check if
the condition changed. This should be used where we return from the
reconcile loop, and only in cases where this is possible log explicitely
at that place.

[OSPK8-416] reduce repeated condition message logging

---

.github/workflows/build-osp-director-operator.yaml

Small typo which results in building containers that are
tagged with master-latest rather then latest for the master
branch. For other branches it's $branch-latest.

Fix typo where TIP is master not main

---

.github/workflows/golangci-lint.yaml

Increase github golangci timeout to 5m as 3m is not enough.

Increase golangci timeout

---

.github/workflows/build-osp-director-operator.yaml

For building containers use pinned 1.13.1 version of Operator SDK.

For building containers use pinned 1.13.1 version of Operator SDK.

---

controllers/openstackvmset_controller.go

/etc/resolv.conf on the controller VMs is still referencing the OCP
cluster DNS server on 172.30.0.10, which is not responding.
This is resulting in slow DNS queries as it wait to timeout before
trying the next/correct server in resolv.conf.
This disables the default DNS config when BootstrapDNS is set, similar
to the baremetal node.

Fix controller VM DNS config

---

.github/workflows/build-osp-director-operator.yaml

Bundle requires login to the redhat.io registry to properly
calculate hashes.

Log in to redhat.io registry for bundle generation

---

api/v1beta1/common_types.go
api/v1beta1/openstackbaremetalset_types.go
api/v1beta1/openstackcontrolplane_types.go
api/v1beta1/openstackprovisionserver_types.go
api/v1beta1/openstackprovisionserver_webhook.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
controllers/openstackbackuprequest_controller.go
controllers/openstackbaremetalset_controller.go
controllers/openstackclient_controller.go
controllers/openstackconfiggenerator.go
controllers/openstackcontrolplane_controller.go
controllers/openstackipset_controller.go
controllers/openstackmacaddress_controller.go
controllers/openstacknet_controller.go
controllers/openstacknetattachment_controller.go
controllers/openstacknetconfig_controller.go
controllers/openstackprovisionserver_controller.go
controllers/openstackvmset_controller.go
go.mod
pkg/common/secret.go
pkg/openstackbackup/funcs.go
pkg/openstackipset/funcs.go

Converts the osbmset controller to use defer function to update/set conditions.
Also:
* Allign defer function of all controllers to log current cond msg
The condition gets updated only if the condition of the CR
changed, but we should log all of them to be able to follow the
reconcilations from the operator log.
* Set condition if finalizer fails to be removed

[OSPK8-413] convert osbmset to defer

---

config/rbac/service_account.yaml

Adds missing `get` and `list` permissions for `virtualmachines` for the Kubevirt fencing agent service account

Fix kubevirt fencing agent SA perms

---

api/v1beta1/common_types.go
api/v1beta1/openstacknetattachment_types.go
controllers/openstacknetattachment_controller.go
go.mod
go.sum

Randomly the following error was seen:
{"level":"info","ts":1643296206.0834217,"logger":"enactmentstatus","msg":"status: {DesiredState:interfaces:\n- bridge:\n    options:\n      stp:\n        enabled: false\n    port:\n    - name: enp6s0\n  description: Linux bridge with enp6s0 as a port\n  mtu: 1500\n  name: br-ex\n  state: up\n  type: linux-bridge\n
...
ERROR: State editing already in progress.\nCommit, roll back or wait before retrying.\n' LastHeartbeatTime:2022-01-27 15:10:06.083365961 +0000 UTC m=+5.790948854 LastTransitionTime:2022-01-27 15:10:06.083365961 +0000 UTC m=+5.790948854}
We suspect that it is could be a result of applying an nncp update
while nmstate is sill applying the config. This patch prevents
the osnetattach controller to update the NNCP CR when the NNCP CR
is not …

[OSPK8-432] Prevent NNCP updates while configuration is in progress

---

README.md
api/v1beta1/openstackcontrolplane_types.go
api/v1beta1/openstackvmset_types.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackvmset.yaml
controllers/openstackcontrolplane_controller.go
controllers/openstackvmset_controller.go
go.mod
go.sum

This patch allows to set the StorageAccessMode and/or StorageVolumeMode
for the VirtualMachineRole disk. StorageAccessMode defaults to
ReadWriteMany as this is required to be able to live migrate
an instance, but could be set to ReadWriteOnce if wanted.
StorageVolumeMode defaults to Filesystem, but when OpenShift
Virtualization with OpenShift Container Platform Container Storage
is used, Block should be used.

[OSPK8-433] Allow to set StorageAccessMode and StorageVolumeMode for VMset

---

api/v1beta1/common_types.go
api/v1beta1/openstacknetattachment_types.go
controllers/openstacknetattachment_controller.go
go.mod
go.sum

Randomly the following error was seen:
{"level":"info","ts":1643296206.0834217,"logger":"enactmentstatus","msg":"status: {DesiredState:interfaces:\n- bridge:\n    options:\n      stp:\n        enabled: false\n    port:\n    - name: enp6s0\n  description: Linux bridge with enp6s0 as a port\n  mtu: 1500\n  name: br-ex\n  state: up\n  type: linux-bridge\n
...
ERROR: State editing already in progress.\nCommit, roll back or wait before retrying.\n' LastHeartbeatTime:2022-01-27 15:10:06.083365961 +0000 UTC m=+5.790948854 LastTransitionTime:2022-01-27 15:10:06.083365961 +0000 UTC m=+5.790948854}
We suspect that it is could be a result of applying an nncp update
while nmstate is sill applying the config. This patch prevents
the osnetattach controller to update the NNCP CR when the NNCP CR
is not …

[OSPK8-432] Prevent NNCP updates while configuration is in progress - v1.2.x backport

---

README.md
api/v1beta1/openstackcontrolplane_types.go
api/v1beta1/openstackvmset_types.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackvmset.yaml
controllers/openstackcontrolplane_controller.go
controllers/openstackvmset_controller.go
go.mod
go.sum

This patch allows to set the StorageAccessMode and/or StorageVolumeMode
for the VirtualMachineRole disk. StorageAccessMode defaults to
ReadWriteMany as this is required to be able to live migrate
an instance, but could be set to ReadWriteOnce if wanted.
StorageVolumeMode defaults to Filesystem, but when OpenShift
Virtualization with OpenShift Container Platform Container Storage
is used, Block should be used.
(cherry picked from commit c53e5504a7d943355b111b09cca92ec79f6d75d7)

[OSPK8-433] Allow to set StorageAccessMode and StorageVolumeMode for VMset - v1.2.x backport

---

api/v1beta1/openstackconfiggenerator_types.go
api/v1beta1/openstackconfigversion_types.go
config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
controllers/openstackconfiggenerator_controller.go
go.mod
go.sum
pkg/openstackconfiggenerator/export.go
pkg/openstackconfiggenerator/volumes.go

A step towards DCN support
Updates the ConfigGeneratorController with logic to harvest
controlPlane Heat parameter exports from the Heat stack.
These are subsequently saved alongside of the ConfigVersion
and will be combined with the overcloud.json data (which
gets generated after deployment) to create the final
set of Ctlplane heat parameter exports.
Also fixes an issue with the ConfigGenerator so that we can create
multiple: previously the ConfigMap name was hard coded preventing
multiple ConfigGenerators from being created.

[OSPK8-434] Harvest Ctlplane exports from heat

---

templates/openstackconfiggenerator/bin/create-playbooks.sh

If the symlink target already exists then a symlink is created within it
instead of updating the symlink source. This could result in the wrong
playbooks being used.

Ensure ansible playbooks symlink is correct

---

.github/create_bundle.sh
.github/workflows/build-osp-director-operator.yaml
.github/workflows/release-osp-director-operator.yaml
Dockerfile.agent
Makefile
scripts/build_and_push_images.sh

The provision-ip-discovery-agent has been removed so drop from the
github actions. Add the operator-agent container instead. Also update
the agent container url in the CSV.

Fix github actions for agent container

---

controllers/openstackbaremetalset_controller.go
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
controllers/openstackvmset_controller.go
pkg/openstacknet/funcs.go
pkg/openstacknetconfig/funcs.go

Right now AddOSNetConfigRefLabel and AddOSNetNameLowerLabels
updated the object when added the required labels to the metadata.
Since the generic way of the functions only updated the object
labels at that point of the reconcilation other object information,
like status got lost.
This changes the two functions to merge the required labels into
the object labels and returns them so that they can be set on the
CR object instead of writing the object in the specific label
functions.

Fix adding osnetcfg and osnet labels on CR

---

api/v1beta1/openstackclient_types.go
api/v1beta1/openstackcontrolplane_types.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackclients.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane_single_net.yaml
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
pkg/openstackbackup/funcs.go
pkg/openstackclient/volumes.go
templates/openstackclient/bin/init.sh

Now that we have the OpenStackDeploy CR workflow we no
longer need to specify GitSecret on the OpenStackClient
and OpenStackControlPlane CRs.
OSPK8-438 #close Closing issue.

Drop GitSecret params from OpenStackClient CRD

---

README.md
pkg/openstacknetconfig/funcs.go
templates/openstackconfiggenerator/config/16.2/network_data.yaml
templates/openstackconfiggenerator/config/16.2/nic/net-config-multi-nic.yaml
templates/openstackconfiggenerator/config/17.0/network_data.yaml

- Use subnetName instead of networkNameLower to identify network
The correct way to identify the network is the subnetName because the networkNameLower can return multiple networks when multiple subnets are used.
- [OSPK8-447] fix network routes for IPv6 multi subnet
The routes parameter of the subnet in `network_data.yaml`, rendered by the operator, use `routes` instead of the expected `routes_ipv6`.
Also the routes parameter rendered in environments/network-environment.yaml which are named <netName>Routes get usually set on the neutron network host_routes property.
```
{{network.name}}Routes:
Routes for the {{network.name_lower}} network traffic.
JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
Routes are added to the host_routes property on the subnet in neutron …
```

[OSPK8-447] Fix multi subnet network identification and routes rendering/template

---

controllers/openstacknetconfig_controller.go

Right now the desired networks is just the sum of all major networks,
while it is the sum of all subnets.

[OSPK8-448] fix osnetcfg 'DESIRED NETWORKS' status

---

config/webhook/manifests.yaml

In eab3f6d203e79590bb95a4a406c15363865cc071 we removed a duplicate
webhook. This updates the config/webhook/manifests.yaml for
the associated change.

Update webhook/manifests.yaml for removed webhook

---

containers/agent/deploy.go
pkg/openstackclient/volumes.go
pkg/openstackdeploy/job.go
templates/openstackclient/bin/tripleo-deploy-term.sh
templates/openstackclient/bin/tripleo-deploy.sh

The tripleo-deploy.sh oc exec shell creates a new process group. Can use
this to terminate the deployment.
Set terminateGracePeriod to 60s for the deploy job container.
Add a signal handler goroutine to the deploy job that exec a new
tripleo-deploy-term.sh script on the openstackclient.
This script will send a SIGTERM to the process group and, if it has not
not terminated after ~30s~50s, send a SIGKILL.

Support interrupting a deploy job

---

go.mod
go.sum

while it is just imported as dependency, bump containerd version to avoid CVE [1] detection
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2011007

Bump containerd to avoid CVE detection with earlier versions

---

api/v1beta1/openstackconfigversion_types.go
config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
pkg/openstackconfigversion/git_util.go

This adds the name of the ConfigGenerator to ConfigVersion
resources so that we can display them when listing.

Add generator name to ConfigVersion

---

README.md
api/v1beta1/openstackconfigversion_types.go
config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
config/rbac/service_account.yaml
containers/agent/deploy.go
controllers/openstackdeploy_controller.go
pkg/openstackdeploy/configmap.go
pkg/openstackdeploy/const.go
pkg/openstackdeploy/job.go

This patch harvests overcloud.json (generated by TripleO Ansible)
after a successful deployment finishes. The results are merged
into other "exported" data from the Heat stack and then written
to the 'tripleo-ctlplane-exports' ConfigMap.
Then intent is to optionally use this ConfigMap alongside
a new ConfigGenerator to implement a multi-stack workflows
like DCN.

Harvest overcloud.json after deployment

---

README.md
config/manifests/bases/osp-director-operator.clusterserviceversion.yaml

This updates the CSV and Readme so that these are marked
as internal.
Also updates the README so that netattachements are identified
as internal there (these are already marked as such in the CSV)

Mark macaddresses, and ipset as internal

---

pkg/openstackconfiggenerator/volumes.go
templates/openstackconfiggenerator/bin/create-playbooks.sh
templates/openstackconfiggenerator/bin/process-heat-environment.py

In a regular OSP16 deployment, parameters are merged by heat-client if
they are a map type.
This does not happen automatically in OSP17 regular deployments and
Director operator (for both 16.x and 17.x) which use ephemeral heat.
The merge strategy must be set explicitly in each environment file.
To workaround this, and remain compatible with existing 16.x
environment files and 3rd party integrations, automatically inject the
merge strategy for all map type parameters if not explicitly set.

Replicate 16.2 parameter merge behaviour

---

README.md
pkg/openstacknetconfig/funcs.go
templates/openstackconfiggenerator/config/16.2/network_data.yaml
templates/openstackconfiggenerator/config/16.2/nic/net-config-multi-nic.yaml
templates/openstackconfiggenerator/config/17.0/network_data.yaml

- Use subnetName instead of networkNameLower to identify network
The correct way to identify the network is the subnetName because the networkNameLower can return multiple networks when multiple subnets are used.
- [OSPK8-447] fix network routes for IPv6 multi subnet
The routes parameter of the subnet in `network_data.yaml`, rendered by the operator, use `routes` instead of the expected `routes_ipv6`.
Also the routes parameter rendered in environments/network-environment.yaml which are named <netName>Routes get usually set on the neutron network host_routes property.
```
{{network.name}}Routes:
Routes for the {{network.name_lower}} network traffic.
JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
Routes are added to the host_routes property on the subnet in neutron …
```

[v1.2.x-backports][OSPK8-447] Fix multi subnet network identification and routes rendering/template

---

Makefile
api/v1beta1/common_openstacknet.go
api/v1beta1/common_webhook.go
api/v1beta1/openstackbaremetalset_webhook.go
api/v1beta1/openstackclient_webhook.go
api/v1beta1/openstackcontrolplane_webhook.go
api/v1beta1/openstackipset_webhook.go
api/v1beta1/openstackvmset_webhook.go
controllers/openstackbaremetalset_controller.go
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
controllers/openstackipset_controller.go
controllers/openstackvmset_controller.go
pkg/openstacknet/funcs.go

- Don't rely on webhookClient in common functions to run local
Right now the webclient is used in a couple of places, which works fine if the operator is deployed in the env, but fails
when running local with webhooks disabled. This changes the functions which uses them and instead pass the client.Client from the caller.
- Add METRICS_BIND_ADDRESS to Makefile allows operator to run local
If port 8080 is already in use to run the operator local it is required to specify a different ports for metrics to bind on. This adds METRICS_BIND_ADDRESS env var to control the address/port metrics to bind to. This allows the operator to be run local like:
`WATCH_NAMESPACE=openstack,openshift-machine-api,openshift-sriov-network-operator ENABLE_WEBHOOKS=false METRICS_BIND_ADDRESS=:8085 make run`

Fixes to allow the operator to run local

---

containers/agent/deploy.go
controllers/openstackdeploy_controller.go
pkg/openstackdeploy/job.go
templates/openstackclient/bin/tripleo-deploy.sh

Pacemaker restart, Octavia, and tripleo-network-config rely on the
stack_action (CREATE or UPDATE) ansible fact or hieradata.
To ensure this works correctly with director operator's ephemeral
heat we need to replicate the tripleoclient logic.
As we do not have the existance of a heat stack to rely on we need a
different approach.
Instead the existance of /var/lib/tripleo-config on any overcloud node
is used to determine the appropriate stack_action setting. This is
passed on the ansible-playbook command line to override the default
stack_action in global_vars (which is always CREATE). The resulting
hieradata is also updated.

[OSPK8-460] Replicate StackAction behaviour for 16.2

---

Makefile
scripts/build_and_push_images.sh

[1] removed the DOCKERFILE and DOCKER_BUILD_DIR env variables
from the docker-build target. As a result for the anget and
the downloader image also the operator image got build and
pushed.
To keep the Makefile as default as possible, this adds new
specific targets, osp-director-operator-agent-image-build and
osp-director-downloader-image-build to build these images.
[1] https://github.com/openstack-k8s-operators/osp-director-operator/commit/efc90f909d9d62928acd33dcf57163d895525869#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R135

Fix agent and downloader image build

---

controllers/openstackbaremetalset_controller.go

Update of BMH objects of provisioned nodes can result in
reprovisioning of the nodes. This change only updates the
BMH spec only on initial deployment when there is no consumer
ref set.
Updating labels is done on any change, which might be needed
on future operator changes.

[OSPK8-545] Do not update BMH spec after provisioning

---

bundle.Dockerfile
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml

* Add annotation to specify the default container [1]
* Reduce debug log level for the sidecar container kube-rbac-proxy from 10 to 0
[1] https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.16.0/#add-annotation-to-specify-the-default-container
[2] https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.17.0/#reduce-debug-log-level-for-the-sidecar-container-kube-rbac-proxy-from-10-to-0

Add missing sdk upgrade changes

---

controllers/openstackbaremetalset_controller.go

DomainName was not correct to render the osbms userdata. Therefore
the DomainName was always empty and not set, which resulted in
osbms nodes to default to short hostname:
```
[root@computehci-1 ~]# hostname
computehci-1
[root@computehci-1 ~]# hostname --short
computehci-1
[root@computehci-1 ~]# hostname --long
computehci-1.osptest.test.metalkube.org
```
And osvmset nodes to fqdn:
```
[root@controller-0 ~]# hostname
controller-0.osptest.test.metalkube.org
[root@controller-0 ~]# hostname --short
controller-0
[root@controller-0 ~]# hostname --long
controller-0.osptest.test.metalkube.org
```
This sets the DomainName correct for the templateParameters that
the osbms cloud-init userdata has the DomainName information set.

Fix compute/osbms hostname to be FQDN

---

api/shared/net.go
api/v1beta1/openstacknet_types.go
api/v1beta1/openstacknetconfig_types.go
api/v1beta1/openstacknetconfig_webhook.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstacknetconfigs.yaml
config/crd/bases/osp-director.openstack.org_openstacknets.yaml
pkg/common/ipam.go
pkg/openstackconfiggenerator/configmap.go
tests/kuttl/tests/openstacknetconfig_error_validation/00-prep.yaml
tests/kuttl/tests/openstacknetconfig_error_validation/01-create_osnet_webhook_validation.yaml
tests/kuttl/tests/openstacknetconfig_error_validation/01-errors.yaml
tests/kuttl/tests/openstacknetconfig_error_validation/osp-director_v1beta1_openstacknetconfig_ipv4_and_ipv6_subnet.yaml
tests/kuttl/tests/openstacknetconfig_error_validation/osp-director_v1beta1_openstacknetconfig_ipv4_mix_ipv6_details.yaml
tests/kuttl/tests/openstacknetconfig_error_validation/osp-director_v1beta1_openstacknetconfig_ipv4_outside_range.yaml
tests/kuttl/tests/openstacknetconfig_error_validation/osp-director_v1beta1_openstacknetconfig_ipv6_in_ipv4.yaml
tests/kuttl/tests/openstacknetconfig_error_validation/osp-director_v1beta1_openstacknetconfig_no_ctlplane_net.yaml

Adds additional validation to check the osnetcfg:
* verifies the a network is tagged as the ctlplane network
* verifies information provided in ipv4/ipv6 section are
actual ipv4/ipv6 information
* verifies that information in the ipv4 section is pure ipv4
* verifies ips provided for AllocationStart, AllocationEnd and
Gateway are part of the network set via the Cidr
* verifies that in a subnet definition there is not both ipv4
and ipv6 provided

[OSPK8-467 OSPK8-472 OSPK8-474] enhance validation for osnetcfg

---

go.mod
go.sum

while it is just imported as dependency, bump containerd version to avoid CVE [1] detection
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2011007
(cherry picked from commit 641e3fc9ef5972fd1602fcaba53ccf730c746eb4)

[v1.2.x backport] Bump containerd to avoid CVE detection with earlier versions

---

go.mod
go.sum

CVE-2021-43565 is fixed in v0.0.0-20211202192323-5770296d904e,
lets bump to current latest.

bump golang.org/x/crypto to v0.0.0-20220507011949-2cf3adece122

---

go.mod
go.sum

CVE-2021-43565 is fixed in v0.0.0-20211202192323-5770296d904e,
lets bump to current latest.
(cherry picked from commit cc43919084a6b6780634969133e9fa6a9e1e0a05)

[v1.2 backport] bump golang.org/x/crypto to v0.0.0-20220507011949-2cf3adece122

---

controllers/openstackvmset_controller.go
pkg/vmset/virtualmachine.go

To prevent an issue when the rootdisk is not the first
disk in the disk list, set BootOrder: 1 [1] on the rootdisk
as this is always the disk the VM should boot from.
[1] https://pkg.go.dev/kubevirt.io/api@v0.51.0/core/v1#Disk

Set BootOrder: 1 on rootdisk

---

controllers/openstackconfiggenerator_controller.go
pkg/openstackconfiggenerator/const.go
templates/openstackconfiggenerator/config/16.2/nic/net-config-multi-nic.role.j2.yaml

Change the VM nic config template to a tripleo role template as it
needs to get the default_route_networks value from roles_data.yaml.
Update the template to only set default routes on the specified
interfaces.

Fix default route handling in VM nic template

---

api/v1beta1/openstacknet_types.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstacknets.yaml

ServiceVIP is right now a required parameter in the IPReservation
type. This prevents update the operator in existing environments
from v1.2.x to later version as there is a validation if existing
object meet the requirements.
ServiceVIP is only used in OSP17 [1] environments and therefore
can be set to optional.
[1] https://github.com/openstack-k8s-operators/osp-director-operator/blob/master/controllers/openstackcontrolplane_controller.go#L885

ServiceVIP to be optional in IP reservation

---

controllers/openstacknetconfig_controller.go

In master of the osp-director-operator OSIPSet got introduced.
During the update from 1.2.x to latest the OSIPSets get created.
The OSNetConfig depends on the OSIPSet to identify which
reservations could be deleted. If an OSIPSet is gone the OSNetConfig
expects that the reservations for the whole role could be delted.
This conflicts during the update as there is no OSIPSet and therefore
the OSNetConfig will delete all reservations, only the nodes which
have static reservations are save to keep their current IPs.
This changes the OSNetConfig behaviour to not delete reservations
for deleted roles if Spec.PreserveReservations is set to true,
which is the default behaviour.

[OSPK8-600] Don't delete role reservations with PreserveReservations true

---

templates/openstackclient/bin/ansible-inventory

The current jq query does not filter deleted hosts correct. Instead
it checks if any node is not deleted and then adds all of the nodes
in a role. This changes the query to delete the deleted marked nodes
from the result.

[OSPK8-601] fix ansible-inventory jq query

---

templates/openstackconfiggenerator/bin/create-playbooks.sh
templates/openstackconfiggenerator/config/17.0/rendered-tripleo-config.yaml

* [1] removed environments/network-isolation.yaml file in wallaby
* [2] introduced the environments/deployed-network-environment.j2.yaml to
created the DeployedNetworkEnvironment + register required resources for
deployed network scenario.
Therefore we remove environments/network-isolation.yaml and
environments/network-environment.yaml from the OSP17.0 stack create
command, remove the rendering of DeployedNetworkEnvironment via the operator
and add instead `-e environments/deployed-network-environment.yaml` for OSP17.
[1] https://github.com/openstack/tripleo-heat-templates/commit/5f97b4136041c2b4fbbf0f5aa407941c3ec61f23
[2] https://github.com/openstack/tripleo-heat-templates/commit/8550b8482fab548d24304f2f7014bd277560eb1c

[OSPK8-602] OSP 17.0 fixes due to ooo changes

---

templates/openstackephemeralheat/bin/heat.conf

Current config version made playbook create to fail on slower/busy ocp cluster.
With these changes taken from a 16.2 traditional undercloud it worked fine.

allign heat tunings with traditional undercloud

---

templates/openstackconfiggenerator/config/16.2/nic/net-config-multi-nic.role.j2.yaml

This was missed when we switched to role nic template a while ago.
As mentioned in [1]:
The OSP 16.2 tripleo nic templates have the <netName>InterfaceRoutes parameter
per default included. The routes parameter rendered in
environments/network-environment.yaml which are named <netName>Routes get
usually set on the neutron network host_routes property and get added to the
role <netName>InterfaceRoutes parameter.
[1] https://github.com/openstack-k8s-operators/osp-director-operator/pull/529

Fix multi subnet routes ... again

---

pkg/bindata_util/render.go
pkg/common/fencing.go
pkg/common/passwords.go
pkg/common/template_util.go

Upstream wallaby deployment fail right now with:
```
2022-08-10T14:00:34.772309024Z 2022-08-10 14:00:30Z [overcloud.ControllerServiceChain]: CREATE_FAILED  resources.ServiceChain: resources.ControllerServiceChain.Property error: resources[88].properties: Property MysqlMariabackupPassword not assigned
2022-08-10T14:00:34.772309024Z 2022-08-10 14:00:30Z [overcloud]: CREATE_FAILED  Resource CREATE failed: resources.ServiceChain: resources.ControllerServiceChain.Property error: resources[88].properties: Property MysqlMariabackupPassword not assigned
```
This is due to this change:
releasenotes/notes/galera-sst-mariabackup-5a667eed1787353f.yaml
features:
- |
When deploying a new HA overcloud, the mysql/galera service can now be
configured to use mariabackup for State Snapshot Transfers (SST) …

Add MysqlMariabackupPassword to generate password list

---

pkg/vmset/virtualmachine.go

We forgot to set the `storageClass` on the PVC for any DataVolumes we create for the OSP VM controllers

[OSPK8-617] Set storage class when creating VMSet DVs

---

containers/image_downloader/entrypoint.sh

Exit immediately instead of trying to extract/convert the non-existant
image.

[OSPK8-623] Better error handling when image download fails

---

containers/image_downloader/Dockerfile

Use an 8 base image upstream since ubi8 is used downstream

Switch to cento:stream8 base for image downloader

---

pkg/common/job_util.go

Need to check the Succeeded count before checking the Failed count when determining the job status.

[OSPK8-626] Fix WaitOnJob when a job is retried

---

bundle.Dockerfile
config/rbac/role.yaml
controllers/openstackvmset_controller.go
pkg/common/job_util.go

Fencing can fail with current RunStrategy RerunOnFailure because
fencing is not a graceful shutdown and kubevirt will jump in and
restart immediately the VM, but fence_kubevirt is waiting for
the successful shutdown state of the VM befor triggering the start.
This changes the RunStrategy to manual and only triggers a start
of the VM once when the VM CR got created. After that its the
responsibility if the end user, or pacemaker to manage the power
state of the VMs.
Resolves: rhbz#2126727

Change RunStrategy of VMs to manual

---

config/rbac/role.yaml
controllers/openstackvmset_controller.go

Fencing can fail with current RunStrategy RerunOnFailure because fencing is not a graceful shutdown and kubevirt will jump in and restart immediately the VM, but fence_kubevirt is waiting for the successful shutdown state of the VM befor triggering the start.
This changes the RunStrategy to manual and only triggers a start of the VM once when the VM CR got created. After that its the responsibility if the end user, or pacemaker to manage the power state of the VMs.
(cherry picked from commit 4c7baead51b196363614bf3e7a682aa33b041162)

[v1.3.x backport] Change RunStrategy of VMs to manual

---

README.md
api/v1beta1/openstackconfiggenerator_types.go
api/v1beta2/openstackcontrolplane_types.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackconfiggenerators.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/samples/osp-director_v1beta1_openstackconfiggenerator.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane_single_net.yaml
config/samples/osp-director_v1beta2_openstackcontrolplane.yaml
config/samples/osp-director_v1beta2_openstackcontrolplane_single_net.yaml
controllers/openstackconfiggenerator_controller.go

The EnableFencing parameter is only used in the ConfigGenerator to auto create templates to enable fencing. Therefore it makes sense to have this parameter in the ConfigGenerator CRD instead of the ControlPlane.
Also as it is a required parameter lets not specify a default and have the user to explicitely either enable or disable it so that the user is being forced to set either state.

Move EnableFencing to OpenStackConfigGenerator

---

README.md
api/v1beta1/openstackconfiggenerator_types.go
api/v1beta2/openstackcontrolplane_types.go
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackconfiggenerators.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/samples/osp-director_v1beta1_openstackconfiggenerator.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
config/samples/osp-director_v1beta1_openstackcontrolplane_single_net.yaml
config/samples/osp-director_v1beta2_openstackcontrolplane.yaml
config/samples/osp-director_v1beta2_openstackcontrolplane_single_net.yaml
controllers/openstackconfiggenerator_controller.go

The EnableFencing parameter is only used in the ConfigGenerator to auto create templates to enable fencing. Therefore it makes sense to have this parameter in the ConfigGenerator CRD instead of the ControlPlane.
Also as it is a required parameter lets not specify a default and have the user to explicitely either enable or disable it so that the user is being forced to set either state.
(cherry picked from commit 6dc6f8b04ba6b30e021893947803b5b666e8d0fb)

[v1.3.x backport] Move EnableFencing to OpenStackConfigGenerator

---

config/manifests/bases/osp-director-operator.clusterserviceversion.yaml

This updates the relatedImages version to match the one we use in config/default/manager_auth_proxy_patch.yaml.
TODO: look into adding a common ENV variable for these

Align kube-rbac-proxy versions

---

api/v1beta2/openstackvmset_types.go

Creating a backup is stuck in quiescing because IsReady() from OSVMSet is using OpenStackVMSetProvisioned instead of VMSetCondReasonVirtualMachineProvisioned as set in the controller at
https://github.com/openstack-k8s-operators/osp-director-operator/blob/v1.3.x/controllers/openstackvmset_controller.go#L1703
This alligns IsReady to use VMSetCondReasonVirtualMachineProvisioned.

Fix IsReady cond reason

---

controllers/openstackcontrolplane_controller.go
go.mod
pkg/common/map.go
pkg/common/passwords.go

Right now the tripleo password secret only gets created once if it does not exist. If a new operator version introduces a new password, this would not get added to the password secret of an existing environment.
This change validates if the password list is missing any entry on the top level. If there is one missing it merges the new password map[string]interface{} into the existing. It only validates if the password list is complete, using the highest level password keys.

Allow updating password secret with new/missing passwords

---

pkg/openstackconfiggenerator/volumes.go
templates/openstackconfiggenerator/bin/create-playbooks.sh
templates/openstackconfiggenerator/bin/process-roles.py

Container image prepare skips any roles with Count=0 but overcloud.j2.yaml does not, resulting in heat errors due to missing image params.
Removing the unused roles from roles_data.yaml avoids the issue and should make the heat stack create more efficient.

Filter out unused t-h-t roles when generating config

---

scripts/baremetalset_cleanup_stale_entries.sh

If the count of an OSBms gets increased above the number of available BMH the OSBms will have compute nodes entries stuck with `hostRef: unassigned`, even when reduce the spec.count again to a number that is available.
This adds a script which can be used to cleanup compute entries from status of osbmset, osnet, osipset and osnetconfig. Also the reservations from the spec of osnet.

[OSPL8-641/OSPK8-642] Add script to cleanup stale baremetalset compute entries

---

scripts/baremetalset_cleanup_stale_entries.sh

If the count of an OSBms gets increased above the number of available BMH the OSBms will have compute nodes entries stuck with `hostRef: unassigned`, even when reduce the spec.count again to a number that is available.
This adds a script which can be used to cleanup compute entries from status of osbmset, osnet and osnetconfig. Also the reservations from the spec of osnet.
(cherry picked from commit 69779be2069903aca29eae5c745bdd63650fe4c3)
improvements to scripts/baremetalset_cleanup_stale_entries.sh
(cherry picked from commit 2f702023d96db4388747fa06a9850415032e5b5d)
(cherry picked from commit 409f53e3a13d36d549d57c7a5596a7433e13686f)

[v1.2.x][OSPL8-641/OSPK8-642] Add script to cleanup stale baremetalset compute entries

---

scripts/baremetalset_cleanup_stale_entries.sh

If the count of an OSBms gets increased above the number of available BMH the OSBms will have compute nodes entries stuck with `hostRef: unassigned`, even when reduce the spec.count again to a number that is available.
This adds a script which can be used to cleanup compute entries from status of osbmset, osnet, osipset and osnetconfig. Also the reservations from the spec of osnet.
(cherry picked from commit 69779be2069903aca29eae5c745bdd63650fe4c3)
improvements to scripts/baremetalset_cleanup_stale_entries.sh
(cherry picked from commit 2f702023d96db4388747fa06a9850415032e5b5d)

[v1.3.x][OSPL8-641/OSPK8-642] Add script to cleanup stale baremetalset compute entries

---

.github/dependabot.yml

Instead of cherry-pick dependabot PRs to v1.3.x branch, which can fail due to inconsitency of go.sum between the branches, enable dependabot for v1.3.x branch.

Enable dependabot for branch v1.3.x

---

templates/openstackclient/bin/tripleo-deploy.sh
templates/openstackconfiggenerator/bin/create-playbooks.sh

The username was not set in the inventory for the "undercloud" host so defaulted to root.
The implicit "localhost" in the inventory also defaults to root.
As a result any files copied locally by ansible were owned by root instead of the cloud-admin user. E.g ceph-ansible and stack_action_override.yaml
This sets the correct user for the undecloud host in inventory and switches from localhost to the "undercloud" host for the stack_action_override.yaml generation.

Use cloud-admin user for local ansible task

---

templates/openstackclient/bin/tripleo-deploy.sh

This appeared to be working when I manually tested it but is not. Turns out the reason root owns the files is tripleo-deploy.sh sets ANSIBLE_BECOME="True". We have to expliciltly disable it if we want the current user.
Fix this for the stack_action_playbook generation. Other cases that hit this such as ceph-ansible will need to be fixed in upstream t-h-t.

Really use cloud-admin user for local ansible task

---

.gitignore
Makefile
bundle.Dockerfile
config/default/manager_default_images_16.2.yaml
config/default/manager_default_images_17.0.yaml
scripts/build_and_push_images.sh

This updates the bundle build process to support having default images for 16.2 and 17.0. Right now tested with
scripts/build_and_push_images.sh . The bundle/index images are now tagged with VERSION-OSP_RELEASE, e.g. 17.0.33-16.2 / 17.0.33-17.0.
In a follow up we have to update the github actions scripts to follow the same and call the latest images latest-16.2/latest-17.0 and v1.3.x-latest-16.2 / v1.3.x-latest-17.0.

Support creating bundle and index image for 16.2 and 17.0

---

templates/baremetalset/cloudinit/userdata
templates/vmset/cloudinit/userdata

Per default for the rhel guest image the BLS entries are for machine-id fffffffffffffffffffffffffffffff . When this id does not match the real machine-id from /etc/machine-id updating via grub2-mkconfig won't get set correct.
This updates the entries for /boot/loader/entries/ffffffffffffffffffffffffffffffff-* to match the current machine-id.

BLS entries in cloud-init for osbms and osvmset

---

containers/agent/deploy.go
pkg/openstackclient/volumes.go
templates/openstackclient/bin/tripleo-deploy.sh
templates/openstackclient/bin/tripleo-export-ceph
templates/openstackconfiggenerator/bin/create-playbooks.sh

Store the CephClientUserName from the heat environment if set, if not then fall back to the default ("openstack").
Add a python script that mimics the python-tripleoclient export ceph logic. Run this after every deploy to generate the ceph export yaml. Also the merge strategy to allow multiple ceph export environment files to be combined. If ceph is not deployed then just generate a valid empty heat environment file. Store the ceph export yaml on the existing exported data config map.

Implement ceph data export

---

templates/openstackclient/bin/tripleo-export-ceph

The tripleoclient export_ceph logic for cephadm assumes ceph_client.yaml is in specific paths which are not correct for OSPdO. Replicate this logic for now using the correct path for OSPdO until it can be parameterized upstream.

Fix ceph export on 17.0

---

templates/openstackclient/bin/init.sh

cephadm creates a key for the user used to deploy ceph in OSP17. This the cloud-admin user does not have permissions to change the ownership of this file in the next restart and the init container fails with:
~~~
+ chown -R cloud-admin: /home/cloud-admin/.ssh
chown: changing ownership of '/home/cloud-admin/.ssh/foo': Operation not permitted 
~~~
For now run the chown using sudo until we figure out other options.

Use sudo to run chown in init.sh of openstackclient

---

.github/workflows/build-osp-director-operator.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/release-osp-director-operator.yaml

Node 12 is out of support[1]. Actions using this need to be updated: actions/checkout@v2 -> v3
actions/setup-go@v2 -> v3
golangci/golangci-lint-action@v2 -> v3
tj-actions/branch-names@v5 -> v6
Replace set-output with new env command [2]
Remaining warnings come from redhat-actions which are in the process of being updated.
[1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ [2] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Update deprecated command and actions in git workflows

---

api/v1beta1/common_openstackbaremetalset.go

If an error occurs during the baremetalset reconile loop the status can contain incomplete hostrefs with just the initial state ("unassigned"). The hostref validation in the next reconcile then fails as it expects a BMH with the literal name "unassigned".
This patch updates VerifyBaremetalStatusHostRefs to skip any hostref that are still in this initial state.

[OSPK8-644] Ignore unassigned hostrefs in VerifyBaremetalStatusHostRefs

---

controllers/openstackbaremetalset_controller.go

If the provisonserver pod redeployes while baremetalhosts are provisioning they would continue attempting to fetch the image from the old provision server ip.
This patch updates the image url on any baremetalhosts that are not fully provisioned to ensure the current provision server ip is used.

Handle provisionserver IP change during bmh provisioning

---

controllers/openstackbaremetalset_controller.go
controllers/openstacknet_controller.go
controllers/openstacknetconfig_controller.go
controllers/openstackprovisionserver_controller.go
controllers/openstackvmset_controller.go
pkg/openstackconfiggenerator/configmap.go
pkg/openstacknetattachment/const.go
templates/baremetalset/cloudinit/networkdata
templates/openstackclient/bin/ansible-inventory
templates/openstackconfiggenerator/config/16.2/rendered-tripleo-config.yaml
templates/openstackconfiggenerator/config/17.0/rendered-tripleo-config.yaml
templates/vmset/cloudinit/networkdata

Query the ctlplane network in osbmet/osvmset instead of assuming 'ctlplane'. Add ctlplane routes to bmh/vm cloud-init and openstackclient pod cni templates. Add routes to DeployServerPortMap/CtlplaneNetworkAttributes. Update ansible inventory script to support multiple ctlplane networks.

DCN: Add support for routed ctlplane subnets

---

controllers/openstackbaremetalset_controller.go

The finalizer name must not exceed 63 characters.
It doesn't have to be globally unique, so just drop the instance name from the finalizer name.

[v1.3.x] [OSPK8-666] Ensure bmset finalizer len does not exceed limit

---

controllers/openstackbaremetalset_controller.go
controllers/openstacknet_controller.go
controllers/openstacknetconfig_controller.go
controllers/openstackprovisionserver_controller.go
controllers/openstackvmset_controller.go
pkg/openstackconfiggenerator/configmap.go
pkg/openstacknetattachment/const.go
templates/baremetalset/cloudinit/networkdata
templates/openstackclient/bin/ansible-inventory
templates/openstackconfiggenerator/config/16.2/rendered-tripleo-config.yaml
templates/openstackconfiggenerator/config/17.0/rendered-tripleo-config.yaml
templates/vmset/cloudinit/networkdata

Query the ctlplane network in osbmet/osvmset instead of assuming 'ctlplane'. Add ctlplane routes to bmh/vm cloud-init and openstackclient pod cni templates. Add routes to DeployServerPortMap/CtlplaneNetworkAttributes. Update ansible inventory script to support multiple ctlplane networks.

[v1.3.x] DCN: Add support for routed ctlplane subnets

---

controllers/openstackprovisionserver_controller.go

Also set deployment strategy to recreate and stop logging a nil err.

[v1.3.x][OSPK8-672] fix provisionserver localImageUrl update

---

templates/openstackconfiggenerator/config/17.0/nic/multiple_nics_dvr.j2

If nodes won't have the External network, like in NovaControl use case, the current nic template won't work. This changes the condition to check External network against role_networks and correct nic index for it.

Fix nic template for split ctlplane

---

config/rbac/role.yaml
config/rbac/service_account.yaml
controllers/openstackprovisionserver_controller.go
pkg/provisionserver/initcontainer.go
pkg/provisionserver/volumes.go

Takes inspiration from https://github.com/openstack-k8s-operators/openstack-baremetal-operator/pull/22 to improve security of the provision server pod by downgrading it from `privileged` to only `hostnetwork`.  Also further improves security by removing the `privileged` and `anyuid` permissions from the controller-manager pod, as they are not needed.

Switch OsProvServer perms to 'hostnetwork' instead of 'privileged'

---

templates/openstackclient/bin/tripleo-deploy.sh
templates/openstackconfiggenerator/bin/create-playbooks.sh

The only reason the git url is parsed is to generate an ssh config file.
Since parsing git urls is non-trivial we can avoid this completely and
just set the required SSH config on the command line via GIT_SSH_COMMAND.
Also remove the hardcoded git user from GIT_SSH_COMMAND

[OSPK8-439] Stop trying to parse git url, just set GIT_SSH_COMMAND

---

api/v1beta1/common_openstackbaremetalset.go
tests/kuttl/tests/openstackbaremetalset_scale/10-assert.yaml
tests/kuttl/tests/openstackbaremetalset_scale/11-assert.yaml

Be more explicit about what is happening during a scale-up of an `OpenStackBaremetalSet`

[OSPK8-735] Improve logging for OSBMS scale-up

---

pkg/openstackconfigversion/git_util.go

More info in https://github.com/go-git/go-git/pull/613 .

Retry for Azure GitOps with capability.ThinPack

---

controllers/openstackclient_controller.go
pkg/openstackconfiggenerator/job.go
pkg/openstackdeploy/job.go
templates/openstackclient/bin/init.sh
templates/openstackconfiggenerator/bin/create-playbooks.sh

FSGroup recursively chowns/chgrps each volume and setgids the dirs. This can interfere with permissions on the openstackclient, which needs to resemble a traditional undercloud host as closely as possible. SSH in particular has strict rule for the ownership and mode of it's files, but there could be other pemissions issues too.
Note FSGroup has no effect on NFS, which we happen to be using in CI, but will affect local volumes, RBD etc... which provide formatted block devices.
Avoid this completely by removing FSGroup and explicitly setting all ownership/modes in the init container.
Jira: [OSP-27993](https://issues.redhat.com//browse/OSP-27993)
Resolves: rhbz#2236085

Stop setting FSGroup

---

go.mod
main.go

Further mitigation against the Rapid Reset exploit

[CVE-2023-44487] Disable HTTP2 in webhook server

---

main.go

This reverts commit 17cfa5bba9a41ac9d2c4bff4d926b48f754a725e. It did not affect the metrics server.

Revert "disable http2 follow up"

---

templates/openstackconfiggenerator/bin/create-playbooks.sh

Extracting/placing default tht files via the script to render the playbooks is intended to allow to override default and rendered tht files. Right now the ordering to copy the files in the final place first copies the tarball and afterwards the default/rendered ones. This prevents from override them via the tarball.
This changes the order to extract the tarball last.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2251800

Fix override of rendered files via tarball

---

templates/openstackclient/bin/tripleo-export-ceph

Swallow and log any exceptions in the ceph export method. Exporting ceph data for cephadm will raise KeyError when external ceph is used. The ceph-ansible data export can also raise KeyErrors if parsing the yaml fails.
Jira: OSPK8-753

[OSPK8-753] Ignore ceph export failure

---

controllers/openstackconfiggenerator_controller.go
pkg/openstackconfiggenerator/configmap.go

Special Redis on OVNDBs roles are not considered in the configgenerator when rendering the template. As a result the required hiera redis_vip was not set
Function lookup() did not find a value for the name 'redis_vip'
This updates the configgenerator to consider Redis and OVNDBs and have the entries like the following in the rendered parameter file:
~~~
OVNDBsVirtualFixedIPs:
- ip_address: 172.17.0.12
use_neutron: false
RedisVirtualFixedIPs:
- ip_address: 172.17.0.11
use_neutron: false
~~~

Fix osconfigenerator for Redis/OVNDBs vips

---

scripts/build_and_push_images.sh

Without this, trying to mirror builds for offline use fails like so:
```
$ oc adm catalog mirror ${INDEX_IMG} ${LOCAL_REGISTRY} --insecure --index-filter-by-os='Linux/x86_64'
...
no digest mapping available for quay.io/andrewbays/osp-director-operator-index:1.3.0-16.2, skip writing to ImageContentSourcePolicy
no digest mapping available for quay.io/andrewbays/osp-director-operator-bundle:1.3.0-16.2, skip writing to ImageContentSourcePolicy
```
Also changes the agent image name from `osp-director-operator-agent` to `osp-director-agent` because the latter is used everywhere else.

Use bundle digest in build script for offline compatibility

---

templates/openstackconfiggenerator/config/common/fencing.yaml

Required to allow additional FencingConfig to be added for compute nodes
Resolves: [OSP-31777](https://issues.redhat.com//browse/OSP-31777)

InstanceHA: Use deep-merge for FencingConfig

---

controllers/openstackbaremetalset_controller.go
templates/baremetalset/cloudinit/userdata

The proper format for authorized keys in cloud-init is a [list](https://cloudinit.readthedocs.io/en/latest/reference/examples.html#configure-instance-s-ssh-keys), but we are using a string instead.  As a result, if multiple keys are desired, none of the SSH keys will work if we place them in that string.

[OSPK8-803] Use list format for SSH authorized keys in OSBMS cloud-init

---

.github/workflows/build-osp-director-operator.yaml
.github/workflows/golangci-lint.yaml
Dockerfile
Dockerfile.agent
Makefile
config/default/manager_auth_proxy_patch.yaml
config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
containers/image_downloader/Dockerfile
go.mod
go.sum
pkg/common/passwords.go
scripts/customize_staged_images.sh

* bumps golang to 1.21
* removes deprecated math_rand.Seed() call
* bumps image_downloader to use centos:stream9
* minor updates to Makefile and bump kube-rbac-proxy image

Bump golang to 1.21

---

config/samples/osp-director_v1beta1_openstackprovisionserver.yaml
docs/README-baremetal-provisioning.md
kuttl-test.yaml
tests/kuttl/tests/openstackbaremetalset_scale/03-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/02-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/03-assert.yaml
tests/kuttl/tests/openstackprovisionserver_unique_port/03-create_openstackprovisionserver.yaml

In OCP 4.16+, the cluster network operator now listens on port 8080 on one of the master nodes.  So in a 3-node master/worker combo scenario, we could run into a collision with the default 8080 port we suggest for the `OpenStackProvisionServer`:
```
tcp   LISTEN     0      4096                                         *:8080                        *:*     users:(("cluster-network",pid=100006,fd=9)) 
```
Let's use 6190 instead, as we do in the newer RHOSO OpenStack Baremetal operator.
Jira: https://issues.redhat.com/browse/OSPK8-820

[OSPK8-820] Using non-conflicting OSProvServer port for OCP 4.16+

---

controllers/openstackconfiggenerator_controller.go
pkg/openstackconfiggenerator/job.go
pkg/openstackconfiggenerator/volumes.go
templates/openstackconfiggenerator/bin/create-playbooks.sh

Add the openstackcontrolplane CAConfigMap CA certs to the trusted certs when running the config generator job as it may need to connect to container registries that use a custom CA (e.g to resolve image tags).

Trust openstackcontrolplane CAs in configgenerator

---

api/v1beta1/common_openstacknet.go
api/v1beta1/openstackipset_webhook.go

In case of backup restore the owner ref needs to get updated by the OpenStackNetConfig controller. If some other reconcile using the OpenStackNet happens first, this reference is missing and e.g. the OpenStackIPSet gets stuck waiting for IPs to be processed.

Return error id OpenStackNet misses OpenStackNetConfig owner ref

---

api/shared/labels.go
api/v1beta1/openstackbaremetalset_webhook.go
controllers/openstackbaremetalset_controller.go
pkg/openstackbackup/funcs.go

When we reworked the way that we handle `OpenStackBaremetalSet` scale-up a while back, we inadvertently introduced logic that could prevent `OpenStackBackup`s from being restored.  We need to make sure that `cleanRestore` backups first allow any existing in-use BMHs to deprovision during cleaning before transitioning to the actual restore.  Failure to do so will possibly cause our newer `OpenStackBaremetalSet` scale-up logic to fail if there are not enough BMHs in the state `available` state to satisfy all `OpenStackBaremetalSet` requests.  If that logic fails, the restore process will error-out and be stuck.

Improve backup and restore functionality for OpenStackBaremetalSets

---

controllers/openstackbaremetalset_controller.go
controllers/openstackclient_controller.go
controllers/openstackcontrolplane_controller.go
controllers/openstackipset_controller.go
controllers/openstackvmset_controller.go

1. We set `currentLabels` to the current `instance.Labels` here: [https://github.com/openstack-k8s-operators/osp-director-operator/blob/905b90ce1481[…]86e3f471f5a894d87472b5/controllers/openstackipset_controller.go](https://github.com/openstack-k8s-operators/osp-director-operator/blob/905b90ce1481fea44886e3f471f5a894d87472b5/controllers/openstackipset_controller.go#L139)
2. Then we set `instance.Labels` equal to the `currentLabels` plus the new label we add by calling `AddOSNetConfigRefLabel()` here: [https://github.com/openstack-k8s-operators/osp-director-operator/blob/905b90ce1481[…]86e3f471f5a894d87472b5/controllers/openstackipset_controller.go](https://github.com/openstack-k8s-operators/osp-director-operator/blob/905b90ce1481fea44886e3f471f5a894d87472b5/controllers/openstackipset_contr …

Fix IPSet label variable usage in AddOSNetConfigRefLabel context

---

controllers/openstackclient_controller.go
controllers/openstackipset_controller.go
main.go

When e.g. a network definition changes, the IPsets have to reconcile to update its information. This allows changing network definition, but needs to be done carefully and tests in a pre-prod env as it is an invasive change.
The process looks like this:
* update the OpenStackNetConfig to do the network change
* validate the IPSet for the role and the OpenStackNetConfig status reflects the new IPs for the nodes
```
172.18.3.20/24
```
* Make sure you have a parameter file to allow update the network config for the role:
```
network-environment.yaml: |
parameter_defaults:
ControllerNetworkConfigUpdate: True
ComputeNetworkConfigUpdate: True
ComputeLeaf1NetworkConfigUpdate: True
```
* use the OpenStackConfigGenerator resource to create a new configversion
* when config generator process …

Reconcile ipset when osnetconfig changes

---

controllers/openstackclient_controller.go
controllers/openstackipset_controller.go
main.go

When e.g. a network definition changes, the IPsets have to reconcile to update its information. This allows changing network definition, but needs to be done carefully and tests in a pre-prod env as it is an invasive change.
The process looks like this:
* update the OpenStackNetConfig to do the network change
* validate the IPSet for the role and the OpenStackNetConfig status reflects the new IPs for the nodes
```
172.18.3.20/24
```
* Make sure you have a parameter file to allow update the network config for the role:
```
network-environment.yaml: |
parameter_defaults:
ControllerNetworkConfigUpdate: True
ComputeNetworkConfigUpdate: True
ComputeLeaf1NetworkConfigUpdate: True
```
* use the OpenStackConfigGenerator resource to create a new configversion
* when config generator process …

[v1.3.x] Reconcile ipset when osnetconfig changes

---

tests/kuttl/tests/openstackbackuprequest_save_restore/02-create_remaining_resources.yaml

We changed the `OpenStackBaremetalSet` `samples/config` YAML a while ago and need to adjust the backup/restore KUTTL test so that it works with it properly

Fix backup/restore KUTTL test to work with current OSBMS config sample

---

api/v1beta1/common_openstacknet.go

If an `OpenStackNet` is missing, we don't have an actual object to reference for producing an error message.  Therefore, just hard-code the Kind into the message, since it won't ever be anything other than `OpenStackNet`.

[OSPRH-12353] Prevent nil pointer panic when network validation fails

---

api/v1beta1/openstackcontrolplane_types.go
api/v1beta1/openstackvmset_types.go
config/crd/bases/osp-director.openstack.org_openstackbackuprequests.yaml
config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
config/crd/bases/osp-director.openstack.org_openstackbaremetalsets.yaml
config/crd/bases/osp-director.openstack.org_openstackclients.yaml
config/crd/bases/osp-director.openstack.org_openstackconfiggenerators.yaml
config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
config/crd/bases/osp-director.openstack.org_openstackdeploys.yaml
config/crd/bases/osp-director.openstack.org_openstackephemeralheats.yaml
config/crd/bases/osp-director.openstack.org_openstackipsets.yaml
config/crd/bases/osp-director.openstack.org_openstackmacaddresses.yaml
config/crd/bases/osp-director.openstack.org_openstacknetattachments.yaml
config/crd/bases/osp-director.openstack.org_openstacknetconfigs.yaml
config/crd/bases/osp-director.openstack.org_openstacknets.yaml
config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml

With 4.16 there is additional validation in olm when the installplan gets deployed. In this validation the CR gets checked against the old v1beta1 CRD, even the object storage version is v1beta2. As there are no conversion webhooks in ospdo the verification fails.
To resolve this this adds the fields which get reported as errors in v1beta1 as optional.

[OSPRH-14001]Make fields optional in v1beta1 to resolve reinstall issues

---

config/default/manager_auth_proxy_patch.yaml
config/manifests/bases/osp-director-operator.clusterserviceversion.yaml

The image gcr.io/kubebuilder/kube-rbac-proxy is deprecated and will become unavailable. Sometime from early 2025 the GCR will go away.
The plan is to update the project to use the new WithAuthenticationAndAuthorization from kubebuilder. Until we are able to do that, use our own hosted kube-rbac-proxy image.

Use quay hosted kube-rbac-proxy image

---

templates/openstackprovisionserver/config/httpd.conf

Security improvement.  Tested in my environment via `curl -v -X TRACE http://192.168.111.10:6190/edpm-hardened-uefi.qcow2`.  Result looked good:
```
< HTTP/1.1 405 Method Not Allowed
< Date: Mon, 17 Mar 2025 09:26:36 GMT
< Server: Apache/2.4.62 (Red Hat Enterprise Linux) OpenSSL/3.2.2
< Allow: 
< Content-Length: 222
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method TRACE is not allowed for this URL.</p>
</body></html>
```
Jira: https://issues.redhat.com/browse/OSPRH-14473

[OSPRH-14473] Disable HTTP TRACE in OpenStackProvisionServer
